### ISSUE TITLE
Exception ArgumentError in Hyrax::GenericWorks#show when viewing a work

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#4937] opened 2021-05-07 15:33 UTC
### Descriptive summary

An exception when viewing a work on the work show page.  See image below.

### Rationale

Exceptions should not be raised when a work is correctly created.

### Expected behavior

Creating a work with all required fields should create the work without error.

### Actual behavior

An exception occurs while the work is saving.

![image](https://user-images.githubusercontent.com/6855473/117472767-3c964b00-af27-11eb-8681-d79eb306f50a.png)

### Steps to reproduce the behavior

1. Login
2. Click Share Work on the home page
3. Select Generic Work for type
4. Fill in required fields and save

Exception is thrown.  Note that the same thing happens with works that already existed.

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment] 2021-05-07 20:32
this seems to be caused by Rails 5.2.6, which is a security release that introduces this error message.

we'll need to come up with and test a fix, and release it on the 2.x and 3.x series'

**Comment by no-reply** [comment] 2021-05-07 21:38
the fix is merged in `main` via https://github.com/samvera/hyrax/pull/4943

i'm working up draft release notes for a release containing this fix.

**Closed** 2021-05-11 00:26 UTC
Labels: bug
