### ISSUE TITLE
Change Visibility column header in Collection and Work Dashboards

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#3459] opened 2018-12-12 22:23 UTC
### Descriptive summary

In Hyrax 2.x, Collection Dashboard and Work Dashboard both have a column called Visibility. At collection level, it is confusing to know if visibility indicator refers to visibility of works in collection or of collection itself.

### Expected behavior

In Collection Dashboard:
Change Visibility column header to: Visibility of Collection

In Work Dashboard:
Change Visibility column header to: Visibility of Work

For both dashboards:
Add column headers and badge names (Private, Public, Institution) to translation file so they can be customized.

### Actual behavior

Badge names are not customizable and Visibility is the name of the column in both dashboards (Collection and Work).

### Related work

#3458 - Conduct usability testing on Collection Dashboard and Work Dashboard

**Comment by blancoj** [comment] 2019-09-11 19:32
@jlhardes I think the badge names (Private, Public, Institution) are already taken care of here:

https://github.com/samvera/hyrax/blob/master/config/locales/hyrax.en.yml#L1440-L1458

Here is the code that makes use of this configuration:

https://github.com/samvera/hyrax/blob/master/app/presenters/hyrax/permission_badge.rb#L33

But the  column header changes on the dashboard do need changing.

**Comment by jlhardes** [comment] 2019-09-11 20:26
This does look like the configuration takes care of the badge names. Thanks!

**Comment by dlim87** [comment] 2019-09-17 18:48
I'm not entirely sure what to QA here, since it doesn't look like there was any work done?

**Comment by no-reply** [comment] 2019-09-21 02:28
I think we should punt this back to Open, since the issue is that we'd like to rename the column by default. Yes?

I think this is a `feedback needed`, since i'd like folks to weigh in on whether the proposed column headers seem good.

@samvera/hyrax-ui-ux-advisors @samvera/hyrax-repo-managers

**Comment by mcdowney** [comment] 2019-10-11 15:10
See also #3432

**Comment by jeremyf** [comment] 2020-07-22 15:04
Closed by #3955

**Closed by jeremyf** 2020-07-22 15:04 UTC
Labels: collections/admin sets, user interface
