### ISSUE TITLE
Adding a thumbnail to a collection does not change the thumbnail in search results

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2008] opened 2017-10-27 21:39 UTC
Descriptive summary

The new thumbnail for the collection appears on the collection show page but does not appear in the search results, the default icon still shows.

Expected behavior

Changing the collection thumbnail should affect both the show page and the search results

Actual behavior

Only the show page is affected.

Steps to reproduce the behavior

Add a thumbnail to a collection after the collection is created.

**more comments at:**
https://github.com/curationexperts/nurax/issues/113

**Comment by orangewolf** [comment] 2018-02-09 22:31
just in case anyone else hits this - it is a solr index not getting updated issue.

**Comment by orangewolf** [comment] 2018-05-31 22:07
@shabububu that does seem to be what we had to do to fix them, though I would make sure that Solr has committed your changes properly. The template update you did seems to solve a slightly different problem.

**Comment by shabububu** [comment] 2018-06-01 12:52
@orangewolf Understood. Thanks for clarifying! I think the descriptive summary might be a bit ambiguous. It really does seem to reflect what I was seeing, but I can understand how an indexing issue could cause this as well, even if I don't see it in my particular case.

**Comment by elrayle** [comment] 2018-10-30 12:48
Are this and #3319 dups?

**Comment by no-reply** [comment] 2018-11-13 00:03
Duplicate of #3164, which is in-progress.

**Closed by no-reply** 2018-11-13 00:03 UTC
Labels: bug
