### ISSUE TITLE
Deactivate Embargoes for Selected Fails

### ISSUE THREAD

**Issue by gamontoya** [samvera/hyrax#3993] opened 2019-09-13 19:07 UTC
### Descriptive summary

QA Testing for Hyrax
- Hyrax Version: 3.0.0.pre.rc1
- Hyrax Branch: master
- Hyrax Revision: 9b2360f3127aee794e7851d97852adaf240ca9ba
- ENV: production
- SHA: 4931f8e90f87f35edf640ad091fdcddb797171bd
- Branch: 2019-09-13-10-00
- Updated: 13 Sep 2019 15:00:26

### Rationale

In the Manage Embargoes section, admin should be able to select multiple items to deactivate the embargoes with one click.

### Expected behavior

On the `Expired Active Embargoes` tab, select multiple items and click on `Deactivate Embargoes for Selected`. Do not click on `Change all files within...` Items are deactivated.

### Actual behavior

On the `Expired Active Embargoes` tab, select multiple items and click on `Deactivate Embargoes for Selected`. Do not click on `Change all files within...` Receive the following Controller Error:

![embargoError](https://user-images.githubusercontent.com/4314914/64888108-fe943700-d61e-11e9-8cc6-0e3c71f47086.png)

### Steps to reproduce the behavior

1. Log in as Administrator
2. Tasks > Manage Embargoes
3. Click on "Expired Active Embargoes"
4. Select two/three items
5. Click on "Deactivate Embargoes for Selected"
6. Do not check off "Change all files within..."
7. Get Controller Error

### Related work

Link to related tickets or prior related work here.

### Notes

Noting that by default, with *Leases* the `Change all files within...` box is checked. Should this be the same for *Embargoes*?

### Related work

- https://github.com/samvera/hyrax/issues/4002

**Comment by dlim87** [comment] 2019-11-06 00:14
I wasn't able to get a video of this behavior, but it is working correctly. The selected expired embargoes are able to be disabled in a batch.

I also did observe the other behavior mentioned in the original issue: 

```Noting that by default, with Leases the Change all files within... box is checked. Should this be the same for Embargoes?```

Is not being checked the intended behavior? That would mean that by default, a disabled embargo would change the permissions on the work, but not the items contained inside it, unless specific actions were taken to also disable the embargo on them. Also note that only works show up on the (expired) embargo list, not the files that continued to be embargoed within them

**Comment by kellyChex** [comment] 2019-11-07 05:12
@no-reply Should we create a ticket to make it so the checkbox to change all files within is selected by default like Leases?

**Comment by no-reply** [comment] 2019-11-08 17:44
Yeah, let's make a separate ticket for this and tag @samvera/hyrax-repo-managers on it for comment.

It seems like the behavior of these check boxes should be made consistent, and my guess is that default-to-checked is the preferred behavior.

**Comment by dlim87** [comment] 2019-11-11 22:35
^ created #4161 for this behavior, closing this ticket

**Closed by dlim87** 2019-11-11 22:35 UTC
Labels: blocker, bug
