### ISSUE TITLE
Editing works shows location URI instead of location label

### ISSUE THREAD

**Issue by mark-dce** [samvera/hyrax#3269] opened 2018-09-12 21:37 UTC
### Descriptive summary

When I enter a *Location* on a new work, the edit form initially displays the correct location label, but when I go back to edit that work, the form displays the URI instead of the label.

QA Testing for Hyrax
Hyrax Version: 2.2.4 
Hyrax Branch: master 
Hyrax Revision: 465571ff1e5aa375e641ef07bbf45ef5d180b74e
© 2018 Samvera-Hyrax 
Nurax Version
ENV: production 
SHA: 48e8c6dcc9a002a823da737cf9b93983710b81bd 
Branch: 2018-09-12-10-00 
Updated: 12 Sep 2018 15:00:28

### Rationale

I can't resolve geoname URIs in my head...

### Expected behavior
![nurax - location](https://user-images.githubusercontent.com/3064318/45454477-acd26d00-b6a9-11e8-8cae-65b80ec18e7e.png)

### Actual behavior
![nurax - location - edit](https://user-images.githubusercontent.com/3064318/45454487-b360e480-b6a9-11e8-9c24-5434a715bc13.png)

### Steps to reproduce the behavior

1. Create a new work in any Hyrax based application - I used nurax
2. Fill in required metadata
3. Save the work
4. Edit the same work

### Related work

https://github.com/samvera/hyrax/issues/1065.

**Comment by adamjarling** [comment] 2018-10-29 19:02
@mark-dce  Does this "Location" item currently work out of the box?   It doesn't for me, although I think at Northwestern here we need to supply some type of credentials to access the API (@kdid )?  If a general user of Hyrax tried this, would they assume it's broken?   Should there be additional help text explaining the context of how this works?   Guess I'm asking because I don't know how it was intended to work.

https://screencast.com/t/QKjDqoSD4wSb

**Comment by adamjarling** [comment] 2018-10-30 14:23
I tried tracing this back as far as I could in the stack, but I'm not sure where the 'label' value is accessible, where it's stored, or how to get it's value onto the `location` element when/where the element markup is constructed.

Seems that for the label to display in the UI, it could be applied to the element when/where it's constructed, as a `data-` attribute.  ie.  `data-display-label`, or something similar.  Then in https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax/autocomplete/linked_data.es6, line #47 can pull the value off the element and declare it under the `label` key, and it makes its way into `select2` for display.   

Hardcoding a value here works, so it's just a matter of finding where this form element is constructed and making sure it's saved label value is accessible.   I'm pretty green still on how all the Hyrax form elements CRUD operations weave together, so if someone is more familiar, might be a quicker fix for them.

**Comment by chrisdaaz** [comment] 2018-11-27 23:03
verified on 

QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.beta1 
Hyrax Branch: master 
Hyrax Revision: b6e511d42bb6466c9f2c9b480ca79d2fe60e5453
© 2018 Samvera-Hyrax 
Nurax Version
ENV: production 
SHA: 83dbf47be5feed18d6965fc3c0d4d81bcee42d52 
Branch: 2018-11-27-10-00 
Updated: 27 Nov 2018 16:00:28

**Comment by j-dornbusch** [comment] 2019-07-31 09:16
@no-reply @adamjarling  In our instance, I found as the origin of the problem the fact that the `Hyrax::ControlledVocabularies::Location` object did not contain its label when it is made available to the view .The only way I found to solve it locally was to force label retrieval before the form is displayed. It's not very elegant because we already store `based_near_label` in Solr. But if tomorrow the `Hyrax::ControlledVocabularies::Location` object arrives already informed with its label, which should be the case, the fetch will disable itself and remain as a fallback mechanism.

```ruby
require 'linkeddata'

class ControlledVocabularyWithFetchInput < ControlledVocabularyInput

  private

  def build_field(value, index)
    super(fetch_if_necessary(value), index)
  end

  def fetch_if_necessary(value)
      value.fetch(headers: {'Accept'.freeze => "application/rdf+xml"}) if value.rdf_label.first == value.rdf_subject.to_s || resource.rdf_label.nil?
  end

end
```
The only drawback of changing the input name is that you have do force the `controlled_vocabulary` class on the `wrapper_html` element, else Javascript will not be find it.

**Comment by no-reply** [comment] 2019-12-23 17:44
this may be fixed by https://github.com/samvera/questioning_authority/pull/307

**Comment by rjkati** [comment] 2021-01-26 21:55
Issue still present in Hyrax 3.0 rc3

**Comment by jeremyf** [comment] 2021-02-02 15:50
I sent @j-dornbusch a Slack message asking for their implementation as a reference to the solution.

**Comment by jeremyf** [comment] 2021-02-02 15:59
To test this issue, I’d like to do this locally. However, in my default installation, when I create a new work, I don’t have a Location field.  I suspect this is a configuration option.  Does anyone have some guidance?  (Also, I suspect testing will require some questioning authority setup, which adds some misery to fixing this)

I posted the above in Slack, and consider this "blocked" until I have more information.

**Comment by jeremyf** [comment] 2021-02-02 16:04
It appears that I needed to first fill out the required fields, then click additional fields. I'm unstuck for the moment.

**Comment by jeremyf** [comment] 2021-02-02 16:15
To trouble shoot this, I'm creating a username for Geonames (as per documentation https://github.com/samvera/questioning_authority/wiki/Connecting-to-GeoNames)

**Comment by jlhardes** [comment] 2021-03-09 21:14
@no-reply has some confidence that this is something that can be fixed and will work on this with @jeremyf.

**Closed** 2022-03-22 20:30 UTC
Labels: bug
