### ISSUE TITLE
Something Went Wrong when adding an existing or new work as a child work

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2108] opened 2017-11-03 20:54 UTC
### Descriptive summary

when adding a child work to a work, we receive Something Went Wrong error page upon submit. 

### Expected behavior

child work should be added to the work without error. 

### Actual behavior

when adding a child work to a parent work and saving, Something Went Wrong.

### Steps to reproduce the behavior

1. Create two works (or have existing two works) in Hyrax rc2
2. Go to one of the works and select the Edit button
3. Navigate to the Relationships tab
4. Attach child work:
   4.1a - attach an **existing** work by searching for it in the relationships window and selecting add
   4.1b - select save for the parent work
   4.1c - Something Went Wrong
   4.2a - attach a **new** work by selecting "attach new work" button
   4.2b - create the new work and save
   4.2c - Something Went Wrong

@mjgiarlo @julesies

**Comment by mjgiarlo** [comment] 2017-11-03 20:55
Here is the traceback:

```
F, [2017-11-03T20:39:20.039778 #29112] FATAL -- : [03388237-b6ae-4a81-b587-558d963edddc] ArgumentError (You attempted to set the property `state' of 1r66j118d to an enumerable value. However, this property is declared as singular.):
F, [2017-11-03T20:39:20.039977 #29112] FATAL -- : [03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/attributes/property_builder.rb:49:in `state='
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:325:in `block (3 levels) in merge_target_lists'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:324:in `each'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:324:in `block (2 levels) in merge_target_lists'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:320:in `tap'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:320:in `block in merge_target_lists'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:317:in `map'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:317:in `merge_target_lists'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:242:in `load_target'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:135:in `to_ary'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_association.rb:286:in `select'
[03388237-b6ae-4a81-b587-558d963edddc] active-fedora (11.5.0) lib/active_fedora/associations/collection_proxy.rb:114:in `select'
[03388237-b6ae-4a81-b587-558d963edddc] hydra-works (0.16.0) lib/hydra/works/models/concerns/work_behavior.rb:49:in `file_sets'
[03388237-b6ae-4a81-b587-558d963edddc] /opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-b64ea8e0d20a/app/controllers/concerns/hyrax/works_controller_behavior.rb:268:in `after_update_response'
[03388237-b6ae-4a81-b587-558d963edddc] /opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-b64ea8e0d20a/app/controllers/concerns/hyrax/works_controller_behavior.rb:101:in `update'
[03388237-b6ae-4a81-b587-558d963edddc] actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
...
```

**Comment by julesies** [comment] 2017-11-03 20:55
Just adding, when I reproduced this - I refreshed after seeing SWW and got the following error: Your changes could not be saved because another user (or background job) updated this Image after you began editing. Please make sure all file attachments have completed successfully and try again. This form has refreshed with the most recent saved copy of the Image.

**Comment by mjgiarlo** [comment] 2017-11-03 21:00
Might you have interest and cycles in taking a gander at this, @jonathandixon?

**Comment by jonathandixon** [comment] 2017-11-03 21:06
I can take a look first thing Monday if no one else takes it before then.

**Comment by jonathandixon** [comment] 2017-11-06 18:09
I'm thinking this may be a bug in ActiveFedora or ActiveTriples. Here is the simplified code of what produces the error:

```
work = GenericWork.new
work.state = Vocab::FedoraResourceStatus.active
work.state = work.state
```

**Comment by jonathandixon** [comment] 2017-11-06 21:08
Hopefully this will be fixed by this PR: https://github.com/samvera/active_fedora/pull/1286

**Comment by no-reply** [comment] 2017-11-08 19:52
I think it would be great to get a regression test in for this, given that the eventual fix turns out to be somewhat awkward.

See: https://github.com/samvera/active_fedora/pull/1290

**Closed** 2017-11-09 15:39 UTC
Labels: blocker, bug, in progress
