### ISSUE TITLE
Multiple work types: broken facets

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/hyrax#148] opened 2016-12-21 23:23 UTC
<a href="https://github.com/hackmastera"><img src="https://avatars.githubusercontent.com/u/845363?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hackmastera](https://github.com/hackmastera)**
_Tuesday Aug 09, 2016 at 20:19 GMT_
_Originally opened as https://github.com/projecthydra/sufia/issues/2437_

----

### Descriptive summary

On 'My Works' works listing, and on search results, 'filter by work type' groups all work types into the same category, called 'Work'.
### Expected behavior

Work types should each have their own facet value.
### Steps to reproduce the behavior
1. Generate a 2nd curation concern using the sufia:work generator
2. create works of both types
3.  navigate to 'my works' or submit blank search.
### Related work

umbrella ticket is #2199

**Comment by mjgiarlo** [comment] 2016-12-21 23:24
<a href="https://github.com/jcoyne"><img src="https://avatars.githubusercontent.com/u/92044?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jcoyne](https://github.com/jcoyne)**
_Wednesday Aug 31, 2016 at 12:31 GMT_

----

This is not a bug, there are two types of facet needed. One for the general type (e.g. Work, Collection, etc.) The other is for specific type (Book, ETD, etc)

CurationConcerns has both:
https://github.com/projecthydra/curation_concerns/blob/master/lib/generators/curation_concerns/templates/catalog_controller.rb#L26
https://github.com/projecthydra/curation_concerns/blob/master/lib/generators/curation_concerns/templates/catalog_controller.rb#L33
I think sufia only has the later.

**Comment by no-reply** [comment] 2018-07-02 18:48
Feedback is needed @samvera/hyrax-repo-managers.

**Comment by vantuyls** [comment] 2019-03-05 17:44
this cannot be reproduced. likely this has been fixed by other changes since the original issue was submitted.

**Closed by vantuyls** 2019-03-05 17:44 UTC
Labels: feedback needed
