### ISSUE TITLE
Investigate ActiveFedora side-effects in Wings Persistence 

### ISSUE THREAD

**Issue by laritakr** [samvera/hyrax#3739] opened 2019-04-09 18:31 UTC
### Descriptive summary

As an object is updated, the wings persister calls `save!` on an Active Fedora version of the resource. The `active_fedora_converter` is accessed to convert a Valkyrie::Resource into an ActiveFedora::Base object. 

As part of this conversion, it calls `ordered_members` and `member_of_collections` on the Active Fedora object it is building, to record the membership attributes of the resource onto the Active Fedora object. 

Both of these methods actually update these membership immediately (the membership containers), meaning that a portion of the persistence is actually happening in the converter. 

Additional investigative testing should be done to press these membership issues, and identify potential pitfalls with this.

### Related work

References https://github.com/samvera/hyrax/pull/3737

**Comment by no-reply** [comment] 2021-03-18 21:13
closing this as a duplicate of #3756

**Closed** 2021-03-18 22:21 UTC
Labels: wings
