### ISSUE TITLE
Breadcrumb on show views should not include "Your Works" with an unauthenticated user

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#1712] opened 2017-09-22 15:17 UTC
When viewing a work as a public user (not logged in) you are presented with breadcrumb "Your Works > Title of Work". If you click on "Your Works" you are asked to sign in. Unauthenticated users should not see "Your works" in the breadcrumbs.

Note: This also happens on the fileset show view. Related: when I refresh the fileset show view, all breadcrumbs disappear including the one linking a fileset to its parent work.

(Using Chrome browser and 2.0.0.beta4)

# Steps to reproduce the behavior

1. Open a new incognito window in Chrome (or the equivalent in your browser of choice)
1. Browse to https://demo.curationexperts.com/
1. Click "Test" work under `Featured Works`
1. Observe that breadcrumbs include `Your Works`

# Screenshots 

![screen shot 2017-09-22 at 11 16 21 am](https://user-images.githubusercontent.com/4356335/30751509-84026c02-9f87-11e7-9886-a4208aa7bc19.png)

# Related work

#911
This ticket is moved from Nurax: https://github.com/curationexperts/nurax/issues/38

**Comment by mjgiarlo** [comment] 2017-09-22 16:48
@julesies I could not reproduce this. I wonder if you saw them in Chrome because they were still in cached referer information? To test this, start up a new incognito window in Chrome and browse to:

https://demo.curationexperts.com/concern/images/1544bp08d?locale=en

Do you see the breadcrumbs? I don't! In which case I think we can close this issue and the one in Nurax.

**Comment by julesies** [comment] 2017-09-22 16:50
@mjgiarlo ah you are right. I don't see it in incognito browser, that is good! will close both.

**Comment by shlake** [comment] 2017-09-22 19:46
Should I crate a new ticket because this "Your Works" bread crumb also appears on the "show file set" page as well (when not logged in - on Chrome & Safari).

https://demo.curationexperts.com/concern/file_sets/v692t621m

![screen shot 2017-09-22 at 3 45 46 pm](https://user-images.githubusercontent.com/3809325/30761703-2c032e26-9fad-11e7-9a1a-b5c6073c0297.png)

**Comment by mjgiarlo** [comment] 2017-09-22 20:04
@shlake I think we can edit this issue to include that information. Another issue though is that if you refresh the fileset show page (just like the work show page), all the breadcrumbs disppear, so you lose the linkage between a fileset and its' work.

**Comment by elrayle** [comment] 2018-04-13 17:39
This issue has been superseded by breadcrumb refactor issues.

Closed: #2818, #2819, #2820, #2829, #2848
Open: #2892 

A review is beginning to compare the refactors to date with the [overall design of the breadcrumb refactor](https://docs.google.com/spreadsheets/d/1Bppr6IRWljrNmEFpVm3vnMlSnuFJs29DES-YDMV_rOs).  Issues will be added for any that do not comply.

**Closed by elrayle** 2018-04-13 17:39 UTC
Labels: breadcrumbs, bug, user interface

**Comment by blancoj** [comment] 2019-06-05 20:30
This is a change I made to our local instance so that the breadcrumb would show up even after the page is refreshed.

https://github.com/mlibrary/deepblue/pull/392/files
