### ISSUE TITLE
Ensure `spec.abilities.admin_set_ability_spec` passes on `.koppie`

### ISSUE THREAD

**Issue by no-reply** [samvera/hyrax#6189] opened 2023-08-24 05:50 UTC
`spec.abilities.admin_set_ability_spec` is failing on koppie builds. there may be a number of reasons for this:

  1. the test setup uses ActiveFedora, and should be refactored to use Valkyrie;
  2. the tests themselves test behavior that only applies to ActiveFedora, and should be turned off by adding the `:active_fedora` rspec metadata;
  3. the unit under test depends on ActiveFedora and needs to be rewritten to use Valkyrie throughout;
  4. some combination of the above.

----

```sh
docker-compose -f docker-compose-koppie.yml build
docker-compose -f docker-compose-koppie.yml up
docker-compose -f docker-compose-koppie.yml exec -w /app/samvera/hyrax-engine app sh -c "bundle exec rspec spec/abilities/admin_set_ability_spec"
```

**Comment by eliotjordan** [comment] 2023-08-24 16:02
Resolving this involves fixing `Hyrax::CollectionType`

**Comment by no-reply** [comment] 2023-08-24 16:43
re `CollectionType`, i think this may be a red herring. see discussion at https://github.com/samvera/hyrax/issues/6196

**Comment by lsitu** [comment] 2023-08-31 15:57
@no-reply I see 17 admin tests failed yesterday. But all tests passed this morning after I retested it from the latest main branch. It looks like the issue is fixed by your PR https://github.com/samvera/hyrax/pull/6249 already. Is the ticket done?

**Comment by lsitu** [comment] 2023-08-31 18:00
Closing it since it's fixed by https://github.com/samvera/hyrax/pull/6249 already.

**Closed by lsitu** 2023-08-31 18:00 UTC
