### ISSUE TITLE
Koppie specs: spec.presenters.hyrax.work_show_presenter_spec raises Hyrax::ObjectNotFoundError

### ISSUE THREAD

**Issue by dlpierce** [samvera/hyrax#6311] opened 2023-09-08 05:12 UTC
### Descriptive summary

`spec/presenters/hyrax/work_show_presenter_spec.rb` is raising Hyrax::ObjectNotFoundError in koppie. This might be related to Wings getting loaded?

```
Hyrax::ObjectNotFoundError:
  Hyrax::ObjectNotFoundError
./lib/wings/services/custom_queries/find_file_metadata.rb:66:in `find_file_metadata_by_alternate_identifier'
./lib/wings/services/custom_queries/find_file_metadata.rb:44:in `find_file_metadata_by'
/usr/local/bundle/gems/valkyrie-3.0.3/lib/valkyrie/persistence/custom_query_container.rb:55:in `block (2 levels) in register_query_handler'
./app/services/hyrax/file_set_file_service.rb:41:in `original_file'
./app/indexers/hyrax/valkyrie_file_set_indexer.rb:29:in `block in to_solr'
./app/indexers/hyrax/valkyrie_file_set_indexer.rb:15:in `to_solr'
./lib/valkyrie/indexing/solr/indexing_adapter.rb:50:in `solr_document'
./lib/valkyrie/indexing/solr/indexing_adapter.rb:44:in `block in persist'
./lib/valkyrie/indexing/solr/indexing_adapter.rb:43:in `map'
./lib/valkyrie/indexing/solr/indexing_adapter.rb:43:in `persist'
./lib/valkyrie/indexing/solr/indexing_adapter.rb:21:in `save'
./app/services/hyrax/listeners/metadata_index_listener.rb:46:in `on_object_membership_updated'
/usr/local/bundle/gems/dry-events-0.2.0/lib/dry/events/bus.rb:44:in `call'
/usr/local/bundle/gems/dry-events-0.2.0/lib/dry/events/bus.rb:44:in `block in publish'
/usr/local/bundle/gems/dry-events-0.2.0/lib/dry/events/bus.rb:36:in `block in process'
/usr/local/bundle/gems/dry-events-0.2.0/lib/dry/events/bus.rb:32:in `each'
/usr/local/bundle/gems/dry-events-0.2.0/lib/dry/events/bus.rb:32:in `process'
/usr/local/bundle/gems/dry-events-0.2.0/lib/dry/events/bus.rb:43:in `publish'
/usr/local/bundle/gems/dry-events-0.2.0/lib/dry/events/publisher.rb:190:in `publish'
./app/services/hyrax/valkyrie_upload.rb:78:in `add_file_to_file_set'
./app/services/hyrax/valkyrie_upload.rb:58:in `upload'
./app/services/hyrax/valkyrie_upload.rb:24:in `file'
./app/jobs/valkyrie_ingest_job.rb:51:in `upload_file'
./app/jobs/valkyrie_ingest_job.rb:28:in `ingest'
./app/jobs/valkyrie_ingest_job.rb:16:in `perform'

...

./spec/presenters/hyrax/work_show_presenter_spec.rb:524:in `block (4 levels) in <top (required)>'
```

**Comment by no-reply** [comment] 2023-10-25 14:16
i'm not able to reproduce this one.

closing it

**Closed by no-reply** 2023-10-25 14:16 UTC
