### ISSUE TITLE
Create new sub-collection leads to NoMethodError in Hyrax::Dashboard::NestCollectionsController#create_collection_under

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5492] opened 2022-03-03 22:44 UTC
### Descriptive summary

Clicking "Create new collection as subcollection" gives rise to error page of "NoMethodError in Hyrax::Dashboard::NestCollectionsController#create_collection_under".

### Steps to reproduce the behavior

1. Go to collection editing page.
2. Clicking "Create new collection as subcollection"
3. Error page appears

**Comment by jlhardes** [comment] 2022-04-06 21:14
This error is still occurring on nurax-pg:

<img width="1216" alt="Screen Shot 2022-04-06 at 5 11 07 PM" src="https://user-images.githubusercontent.com/3440166/162071649-139d1d31-3fa4-479b-9ee6-361e93f27bc7.png">

### Steps to reproduce the behavior

* From Dashboard -> Collections create a collection of type "nesting only"
* From Dashboard -> Collections, click the title of the collection
* Click Create new collection as subcollection (this is where the error occurs that is in the screenshot)

**Comment by no-reply** [comment] 2022-05-11 20:48
@jlhardes i'm confused if this is an issue with `nurax-pg` / valkyrie support, or if it's a base hyrax issue.

i don't think any of the `NestCollectionsController` supports valkyrie. AFAIK, this is the only thing not passing the full test suite when using a valkyrie collection model.

this was coming up to the top of my ToDo list, but i'm concerned about taking that work on if the controller is broken against the ActiveFedora branch.

**Comment by jlhardes** [comment] 2022-05-11 21:07
This was from testing nurax-pg so it is valkyrie-specific. I just tested again and the error is still occurring on nurax-pg. Does that help?

**Comment by gamontoya** [comment] 2022-09-13 19:21
@cjcolvar @blancoj I'm still seeing the error (testing on nurax-pg)

![5492](https://user-images.githubusercontent.com/4314914/189990993-3afd0f77-9472-4504-a0a9-3ccdc465e81e.png)

**Comment by cjcolvar** [comment] 2022-09-13 19:35
The fix hasn't been merged and deployed to nurax-pg yet.  I can tag you for retesting once it is deployed.

**Comment by eporter23** [comment] 2023-01-23 18:31
I was able to successfully create a sub collection within a User Collection type that I had previously created, using the original steps in the ticket description. I am seeing another error when trying to open the All Collections tab within the Dashboard however.  
<img width="652" alt="Screen Shot 2023-01-23 at 1 29 03 PM" src="https://user-images.githubusercontent.com/13855987/214120827-2c8493fd-c028-4694-9c2c-df8252714291.png">

<img width="1135" alt="Screen Shot 2023-01-23 at 1 29 18 PM" src="https://user-images.githubusercontent.com/13855987/214120850-c85a468b-0bdf-4177-bd7d-07c05fbd8086.png">

**Comment by jlhardes** [comment] 2023-01-23 18:52
I think this sub-collection issue is fixed. It works for me testing locally on koppie the same as you reported. The All Collections tab on nurax-pg is not working when logged in as an admin user. Testing locally on koppie as an admin user, the All Collections tab is working so it might be something specific to indexing on nurax-pg?

**Comment by eporter23** [comment] 2023-01-23 19:25
Thanks @jlhardes I was wondering if it was a nurax-pg specific error since it seemed to reference a specific Collection Type id being missing. I'll go ahead and close this one.

**Closed by eporter23** 2023-01-23 19:25 UTC
Labels: Collection, priority, valkyrization
