### ISSUE TITLE
Login Routing Problems

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/hyrax#3418] opened 2018-11-16 15:39 UTC
### Descriptive summary

Hyrax Master (2.4.x) -- Firefox

There are odd things happening after a user logs in. 

### Expected behavior

Login should bring user to the Dashboard.

### Actual behavior

- Logging in as an admin will open up the thumbnail to a work in the browser:
- Loggin in as a general user will open to the homepage with a message saying "You are not authorized to access this page.

### Steps to reproduce the behavior

1. Go to https://nurax-dev.curationexperts.com
2. Login

### Related work

Link to related tickets or prior related work here.

**Comment by no-reply** [comment] 2018-11-17 03:50
I can't reproduce this using the steps provided, either on Nurax or on the 2.x-stable branch.

Can we dig in a bit deeper and see what we're up against here?

**Comment by gamontoya** [comment] 2018-11-19 18:48
@chrisdaaz This is what I see when logging in as admin using FFox

![ffox](https://user-images.githubusercontent.com/4314914/48728020-a6e89300-ebe8-11e8-84bb-582725eea8ef.png)

**Comment by gamontoya** [comment] 2018-11-19 18:51
Logged in a `user`

![user](https://user-images.githubusercontent.com/4314914/48728146-ff1f9500-ebe8-11e8-9a3f-f8feccf2a231.png)

**Comment by chrisdaaz** [comment] 2018-11-27 17:59
this seems to only be happening to me with firefox.

unable to reproduce with chrome and MS edge

**Comment by julesies** [comment] 2018-11-27 18:19
I was using chrome, FWIW.

**Comment by chrisdaaz** [comment] 2018-12-04 18:33
i am no longer able to reproduce this, and neither is @gamontoya . @julesies is still experiencing this issue on Mac and Safari. 

@kdid if you're unable to reproduce this with browserstack, then perhaps the issue was isolated to nurax and went away after a recent deploy. in this case, feel free to close.

**Comment by kdid** [comment] 2018-12-05 16:38
Closing. We'll reopen if we can figure out how to reproduce.

**Closed by kdid** 2018-12-05 16:38 UTC
Labels: blocker, bug, user interface
