### ISSUE TITLE
Batch editing permissions fails silently

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#2827] opened 2018-03-21 19:23 UTC
https://github.com/curationexperts/nurax/issues/242

**Descriptive summary**
Batch editing works for changes in permissions is not working. Batch editing works for metadata changes works fine.

I tested adding an editor for 3 works and changing visibility from private to public. both failed with no error presented to the user. 

**Steps to reproduce the behavior**
Log in and go to Dashboard: Works
Select several works, click Edit
Click permissions tab and make changes
Go to individual works to see no change.
Related work
per slack convo could be related to the indexing problems.

**Comment by newmanld** [comment] 2018-03-22 15:56
As a counterpart to this issue, the "Currently Shared With" is not picking up editors - when the same editor is an editor on all works on the batch. So one can not use this area in the Permissions tab to add or remove editors, perhaps also other permissions.   I was testing in v2.1.0_beta1b_qa on nurax.curationexperts.com

**Comment by laritakr** [comment] 2018-03-23 21:17
I believe this issue is regarding batch editing is resolved by the indexing fixes. @julesies can you please verify once nurax is updated?

**Comment by dunn** [comment] 2018-03-29 17:40
I can't reproduce on Hyrax master as of 322d04fd98c9789a4fa9ffecd840440b181bc979

**Comment by julesies** [comment] 2018-03-29 17:46
i'm unsure if nurax has this update, but will test to confirm when it does!

**Comment by julesies** [comment] 2018-03-29 17:47
@newmanld did you write up a separate issue for your above comment? if not can you? Thanks!

**Comment by dunn** [comment] 2018-03-29 21:39
From what I can tell, the second issue
> In addition, batch editing roles (ie. adding a viewer) is not updating either the work or the file.

is because work permissions are updated via the actor stack, specifically the `ApplyPermissionTemplateActor`.  The editing of a single work is handled by `WorksControllerBehavior`, which plugs into the actor stack: https://github.com/samvera/hyrax/blob/master/app/controllers/concerns/hyrax/works_controller_behavior.rb#L97-L99

Batch edits are handled by the `BatchEditsController`, which does not: https://github.com/samvera/hyrax/blob/master/app/controllers/hyrax/batch_edits_controller.rb#L48-L53

I don't think I understand the actor stack well enough to integrate it into the Batch Edits controller.

**Comment by elrayle** [comment] 2018-03-29 22:41
PR #2866 fixes apply visibility to all works.

Remaining Work:
* Apply sharing changes to all works.  See @dunn note above for more info.

**Comment by elrayle** [comment] 2018-04-19 17:50
To reproduce:
* Dashboard -> Works
* click checkboxes beside a few works
* Edit Selected
* Permissions tab
* add an editor
* Save

Verify all works have the editor user.

**Closed** 2018-04-23 13:54 UTC
Labels: blocker, bug, in progress
