### ISSUE TITLE
Adding a file larger than 500 MB to a work does NOT error

### ISSUE THREAD

**Issue by jillpe** [samvera/hyrax#6179] opened 2023-08-23 20:16 UTC
# Summary
This resulted from testing W_1.26 on the Hyrax QA Guide: https://docs.google.com/spreadsheets/d/1_eGSAtwWwR-0XUQo0PFtCtWbJ34YPres/edit#gid=1419227219

When creating a work and adding a file that is larger than 500 MB, there is no error message that alerts the user. Although, the work never saves/goes through, the user is able to click save work without being alerted the file is too large.

**Comment by no-reply** [comment] 2023-08-23 22:04
is this a duplicate of #6069 ?

**Comment by rjkati** [comment] 2023-08-24 13:16
Yes this is a duplicate of #6069. An interim solution was implemented in #6079, which adds a note about the upload limits. This note is present on pg.nurax.

**Comment by rjkati** [comment] 2024-03-13 17:51
duplicate of #6069

**Closed by rjkati** 2024-03-13 17:51 UTC
