### ISSUE TITLE
Authorize Proxies drop down is misbehaving

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#1039] opened 2017-05-24 20:09 UTC
In the Edit Profile page, the Authorize Proxies drop down/search box is misbehaving, making it unclear to the user that the field is actually taking the information. 

Expected Behavior:
Enter a few letters into the drop down field and then select a username to be the proxy. The name of the proxy should persist somewhere (probably in the drop down/search field) so that the user knows that they have actually selected a proxy. 

Actual Behavior:
Entering a few letters into the drop down/search field returns user names as expected, but when a user is selected from the list, the Authorize Proxies field resets to a blank drop down.

**Comment by mjgiarlo** [comment] 2017-05-31 21:48
@vantuyls I'm seeing the username pop over into the Current Proxies area. You aren't seeing that? Are you seeing this in Hyku or Hyrax? If Hyku, which deployment? If Hyrax, which version?

**Comment by vantuyls** [comment] 2017-05-31 22:01
Hyrax master. Want video?

**Comment by mjgiarlo** [comment] 2017-06-01 15:04
@vantuyls I'd love it. (Though I can't seem to do flash. I know I'm a problem child. :disappointed:)

**Comment by jcoyne** [comment] 2017-06-01 15:20
@vantuyls can you draw him a picture in paintbrush (export to gif as @mjgiarlo can't read bmp files either ;) )

**Comment by mjgiarlo** [comment] 2017-06-01 16:09
brb, recompiling my kernel

**Comment by rjkati** [comment] 2021-05-17 13:51
In Hyrax 3.0.2, I can search for a user in the "Authorize Proxies" drop down menu and click on a username to select the user as a proxy. When I select a user, their username appears in the "Current Proxies" list and the "Authorize Proxies" field resets to a blank dropdown. This behavior occurs in Firefox 88.0.1 and Chrome 90.0.4430.212.

@jlhardes what is the expected behavior?

**Comment by jlhardes** [comment] 2021-05-17 16:57
The username being added to the Current Proxies list seems to be the outcome for selecting a username from that drop-down. There's no Add button or Save button, which might be considered a more expected set of form controls, but this seems to be functioning without any errors so I think we can close this for now.

**Closed by jlhardes** 2021-05-17 16:57 UTC
Labels: bug, feedback needed
