### ISSUE TITLE
Empty collections displayed when clicking "View collections of this type" after trying deleting non-empty collection type

### ISSUE THREAD

**Issue by MPLSFedResearchTZ** [samvera/hyrax#5522] opened 2022-03-11 21:32 UTC
### Descriptive summary

When clicking the button "View collections of this type" it should display all visible collections of this collection type.

![image](https://user-images.githubusercontent.com/93392603/157973604-34eb8287-2f62-463b-baea-e5748ff3b684.png)

### Steps to reproduce the behavior

1. Go to Settings-> Collection types to get a list of collections types.
2. Deleting a collection type that contains some collections of this type.
3. The pop-up box shows up which contains two buttons, "Cancel" and "View collections of this type"
4. Click the "View collections of this type"
5. The user is supposed to see all the collections of this type but it shows an empty list.

**Comment by eliotjordan** [comment] 2022-03-17 22:28
I'm unable to replicate this ticket. @elrayle Is it possible some of the collection work that's already been done has fixed this?

**Comment by MPLSFedResearchTZ** [comment] 2022-03-18 14:43
The issue is still there. I reproduced it by deleting this "test collection type" collection type I created.
![image](https://user-images.githubusercontent.com/93392603/159024284-ecce74b7-69d6-434b-9b31-33accf50e927.png)

**Comment by eliotjordan** [comment] 2022-03-18 15:21
@MPLSFedResearchTZ Couple of questions:

1. Are you testing this using the Dassie or EngineCart test apps?
2. Have you pulled in the latest commits on the main branch?
3. If so, try creating a new collection type and a new collection, and then test the delete.

**Comment by eliotjordan** [comment] 2022-03-18 16:38
@MPLSFedResearchTZ nurax-pg is ~55 commits behind Hyrax main. I'll see about getting that updated and deployed.

**Comment by elrayle** [comment] 2022-04-04 19:53
I updated to latest Hyrax and this still fails on nurax-pg.  The problem is the filtering.  It filters by `Collection Type > nesting only` && `Collection Type > Collection`.  The second filter is actually the `has_model_ssim` which is `Hyrax::PcdmCollection` on nurax-pg.  I don't see the need for the second filter.  Since the results are displayed on `Dashboard -> Collections` which already filters to collections, this seems redundant.

**Comment by jlhardes** [comment] 2022-08-18 21:12
Remaining work listed in [#3820](https://github.com/samvera/hyrax/issues/3820#issuecomment-880084599) - Replace calls to ActiveFedora::Base.where (removes 7 refs to ActiveFedora) might be needed for this issue

**Comment by jessicahilt** [comment] 2023-08-07 17:37
Let's try to reproduce this problem first. If reproducible, cross-check against in 3820.

**Comment by mcritchlow** [comment] 2023-08-23 13:51
I'm unable to reproduce this with nurax on the `pg` branch (testing with @OkayKris )

When clicking on `Delete` for the collection type I created (after creating/associating a few collections with it) I get:

![image](https://github.com/samvera/hyrax/assets/67506/d0722c8e-1b15-41e3-8bec-75a6b9a2b0a3)

And then

![image](https://github.com/samvera/hyrax/assets/67506/4253fccf-370b-494f-89e3-12d3017986a7)

However, when I then navigate to `Collections` in the UI, I get the following error:

![image](https://github.com/samvera/hyrax/assets/67506/e7dbcb2f-b3f7-4cc6-8852-d3dd28b3f9fc)

**Comment by no-reply** [comment] 2023-08-30 20:13
@mcritchlow `ActiveFedora::Base.where(Hyrax.config.collection_type_index_field.to_sym => to_global_id.to_s).count` doesn't hit FCRepo, just solr. if the solr index is configured correctly, i'd expect that code to work.

it seems like this comment https://github.com/samvera/hyrax/issues/5522#issuecomment-1087951203 correctly identifies the issue. the search builder used for the `My::CollectionsController#index` action is filtering out all collections, because it limits `has_model_ssim` to `Collection` which isn't a model name that gets indexed in Koppie.

**Comment by OkayKris** [comment] 2023-08-31 17:52
@no-reply still unable to replicate the original issue, the modal notifying the user that there are multiple collections in a collection type is being bypassed/ignored as referenced by this [5522 comment](https://github.com/samvera/hyrax/issues/5522#issuecomment-1693535198)

**Comment by no-reply** [comment] 2023-08-31 17:56
@OkayKris i'm confused. i thought that this issue was fixed by the removal of `RoleManager`?

**Comment by OkayKris** [comment] 2023-08-31 17:59
@no-reply i assumed so as well, but i guess it's something completely different. my and @mcritchlow 's guesses were there is something going on with the relationship of collections and collection types or something is wrong with assigning a collection to a collection type

**Comment by no-reply** [comment] 2023-08-31 18:18
@OkayKris that seems like a leap to me, and i'm wondering if we could start at trying to get a failing test.

it may also help to say where you're observing the behavior you describe (on what branch/commit, in what environment). i wasn't seeing it yesterday on the now merged work.

**Comment by OkayKris** [comment] 2023-08-31 18:47
@no-reply sure working on latest commit on main in `koppie` with the fix from #6268 

i feel that `./spec/features/collection_type_spec.rb:369` should fail because of `expect(page).to have_content(not_empty_collection_type.title)` but this passes with Shaun's fix, however when trying to replicate with Matt's work in dev, it fails. we:

1) create a collection type
2) create multiple collections of that collection type
3) optional, create works that go into collections
4) delete collection type 
5) expect `You cannot delete this collection type because one or more collections of this type have already been created.`

but we don't get that modal, instead we're allowed to delete the collection type right away.

aside from this test, i assume we're expecting this to execute https://github.com/samvera/hyrax/blob/main/app/models/hyrax/collection_type.rb#L156-L160

to give us a `deleteDenyModal` flag (lack of a better term here) such that the `<!-- Modal window: Can't delete the collection type -->` pops up. 

instead, we're taken straight to `deleteModal` where `<!-- Modal window: Delete collection type confirmation -->` if that makes sense?

**Comment by no-reply** [comment] 2023-08-31 18:52
@OkayKris i'm still confused. is the behavior you're experiencing that the feature test fails or that, using some other setup, you're able to create a circumstance where it fails?

it dosen't fail for me, and if the issue is the latter case, i think some more information is needed. what's different between how you're setting up your environment and how the feature spec does it?

**Comment by OkayKris** [comment] 2023-08-31 19:12
@no-reply apologies! no test is failing, which i feel is why i'm confused. `./spec/features/collection_type_spec.rb:369` which means then when we recreate this on the dashboard, we should get the modal the prevents us from deleting the collection type. 

this test is under the context `context 'when collections exist of this type'`, where `it 'shows unable to delete dialog and forwards to All Collections with filter applied'` where we expect this to pop up:

```
let(:deny_delete_modal_text) do
        'You cannot delete this collection type because one or more collections of this type have already been created. ' \
        'To delete this collection type, first ensure that all collections of this type have been deleted.'
```

now, running `docker compose -f docker-compose-koppie.yml exec -w /app/samvera/hyrax-engine app sh -c "bundle exec rspec ./spec/features/collection_type_spec.rb:355"` passes which is good, but i can't get the same result when im physically trying to recreate this on the dashboard.

**Closed** 2023-09-06 12:46 UTC
Labels: Effort: Minor, valkyrization, solr filter
