### ISSUE TITLE
Hyrax::CurationConcern.actor_factory not being set correctly

### ISSUE THREAD

**Issue by whunter** [samvera/hyrax#1398] opened 2017-07-27 19:46 UTC
### Descriptive summary

Version: hyrax (1.0.3)

Traceback:

```
undefined method 'build' for nil:NilClass

vendor/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/services/hyrax/curation_concern.rb:13:in `actor'
vendor/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/controllers/concerns/hyrax/curation_concern_controller.rb:125:in `actor'
vendor/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/controllers/concerns/hyrax/curation_concern_controller.rb:45:in `create'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:186:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `block in instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:124:in `process'
vendor/bundle/ruby/2.3.0/gems/actionview-5.1.2/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundle/ruby/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/ldp_cache.rb:26:in `call'
vendor/bundle/ruby/2.3.0/gems/flipflop-2.3.1/lib/flipflop/feature_cache.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:556:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:20:in `block in call'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `catch'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:522:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"0a/Dl5NzILHmGcJrD2n9X2qiZRF0LwKI5MnodDaJpbMRqsIjqYF3JsD+cLBIu9iyBl3m76ntFZh+HYC8QmVo0g==",
 "composition"=>
  {"title"=>["asdf"],
   "creator"=>["asdf"],
   "keyword"=>["asdf"],
   "rights"=>["http://creativecommons.org/licenses/by/3.0/us/"],
   "contributor"=>[""],
   "description"=>[""],
   "publisher"=>[""],
   "date_created"=>[""],
   "subject"=>[""],
   "language"=>[""],
   "identifier"=>[""],
   "based_near"=>[""],
   "related_url"=>[""],
   "source"=>[""],
   "resource_type"=>[""],
   "admin_set_id"=>"admin_set/default",
   "member_of_collection_ids"=>[""],
   "visibility"=>"open",
   "visibility_during_embargo"=>"restricted",
   "embargo_release_date"=>"2017-07-26",
   "visibility_after_embargo"=>"open",
   "visibility_during_lease"=>"open",
   "lease_expiration_date"=>"2017-07-26",
   "visibility_after_lease"=>"restricted"},
 "uploaded_files"=>["2"],
 "new_user_name_skel"=>"",
 "new_user_permission_skel"=>"none",
 "new_group_name_skel"=>"Select a group",
 "new_group_permission_skel"=>"none",
 "agreement"=>"1",
 "locale"=>"en"}
```

### Rationale

When I attempt to create a work through the hyrax GUI at https://localhost/concern/work/new?locale=en I get the following error when I click save after adding metadata and attaching a file.
`undefined method 'build' for nil:NilClass` line 13 in hyrax-1.0.3/app/services/hyrax/curation_concern.rb

### Expected behavior

Application should create a work object and redirect to the work's show page.

### Actual behavior

Application throws `undefined method 'build' for nil:NilClass` exception
It seems as though `Hyrax::CurationConcern.actor_factory` is not being set. It should be set here
https://github.com/samvera/hyrax/blob/v1.0.3/lib/hyrax/engine.rb#L70

### Steps to reproduce the behavior

1. Navigate to the /concern/work/new page in the hyrax application
2. Enter metadata
3. Attach file
4. Click "Save"

Note: A work can be successfully created by setting:
`Hyrax::CurationConcern.actor_factory = Hyrax::ActorFactory` immediately before the `actor_factory.build` call here:
https://github.com/samvera/hyrax/blob/v1.0.3/app/services/hyrax/curation_concern.rb#L13

### Related work

Link to related tickets or prior related work here.

**Comment by mjgiarlo** [comment] 2017-07-27 21:00
@whunter for the heck of it, what if you tried moving this line https://github.com/samvera/hyrax/blob/v1.0.3/lib/hyrax/engine.rb#L70 to line 24 of the same file?

**Comment by mjgiarlo** [comment] 2017-07-27 21:01
@whunter I'm surprised this isn't cropping up in CI builds. Do you know how others could reproduce this?

**Comment by whunter** [comment] 2017-07-27 21:31
@mjgiarlo I'll try moving that line up to the beginning of the after_initialize block. 
When I asked about this on Slack I did so with the assumption that I had missed a step (or steps) in setting up the application. If that was not the case then yeah, I would think that others would be able to reproduce.

**Comment by mjgiarlo** [comment] 2017-07-27 21:42
@whunter Is your application under version control and shareable? Or do you have documentation of the steps you took? I can't think of any missed steps that would result in this error, so I doubt it's you! The above would make it easier to troubleshoot the issue, given that CI seems to be hunky-dorey. Thanks for reporting this.

**Comment by mjgiarlo** [comment] 2017-08-01 21:46
@whunter See #1409!

**Comment by whunter** [comment] 2017-08-01 23:02
That's great! So I guess someone was able to reproduce?

**Comment by jcoyne** [comment] 2017-08-01 23:20
@whunter *I* was unable to reproduce, this was just a guess that this might fix it.

**Comment by mjgiarlo** [comment] 2017-08-02 15:36
@whunter When you confirm this fix works for you, I will approve and merge this PR. (You may need to make a similar change to 1.x to test this out. In which case, after I merge this PR, I will backport it to `1-0-stable` so you can use it.)

**Closed** 2017-08-04 20:21 UTC
Labels: feedback needed, in progress
