### ISSUE TITLE
encoding bug of `"` for non-default language

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3421] opened 2018-11-16 17:17 UTC
### Descriptive summary
encoding bug of &ldquor; &ldquo; for German  language  

### Expected behavior
Übertragung des Eigentums von „Fedora“ 

Guillemets are preferred in German.  I started to correct this earlier in https://github.com/samvera/hyrax/pull/2443/files
 So #3421 requests to display all quotations as for example: https://nurax-dev.curationexperts.com/concern/generic_works/gm80hv50h/edit?locale=de
 ... im Abschnitt „Freigeben“ einen bestimmten ... 

 
### Actual behavior
https://nurax-dev.curationexperts.com/works/hd76s024f/transfers/new?locale=de

### Steps to reproduce the behavior
1. https://nurax-dev.curationexperts.com/works/hd76s024f/transfers/new?locale=de

### Related work

Link to related tickets or prior related work here.

**Comment by jmfrenzel** [comment] 2019-01-23 18:06
Changed description,  see:
https://github.com/samvera/hyrax/pull/3476#issuecomment-456905528

**Comment by jmfrenzel** [comment] 2019-04-17 18:41
![Quotes](https://user-images.githubusercontent.com/30596226/56312711-168b8b80-6151-11e9-8ee6-285d1bd6f93e.png)

**Comment by cjcolvar** [comment] 2019-05-13 17:39
Was this fixed by https://github.com/samvera/hyrax/pull/3767?

**Comment by jmfrenzel** [comment] 2019-05-13 18:52
No it wasn't. 
The template does not render correctly, see
https://github.com/samvera/hyrax/blob/3af966faf937f10446e4983ca1f384df5ca9c2da/app/views/hyrax/transfers/new.html.erb#L2  
This is the line in the German locale being affected.
https://github.com/samvera/hyrax/blob/3af966faf937f10446e4983ca1f384df5ca9c2da/config/locales/hyrax.de.yml#L1181
To me I seems the is with the variable %{work_title}

The other non working rendering is the help text on the same page  
https://github.com/samvera/hyrax/blob/3af966faf937f10446e4983ca1f384df5ca9c2da/config/locales/hyrax.de.yml#L1180

**Comment by fritzfreiheit** [comment] 2019-05-22 19:44
I think a general solution to this problem would be to allow for html characters to remain html characters when processed by I18n.translate, rather than replace strings like '&ldquor;' with '&amp;ldquor;'.

**Comment by fritzfreiheit** [comment] 2019-05-23 15:01
@jmfrenzel -- I did some research into this, and it turns out that the `I18n.translate` mechanism accepts hex and unicode escapes, so you can do this (note the double quotes are necessary):

`title: "\xDCbertragung des Eigentums von \u201E%{work_title}\u201D"`

Produces:

`Übertragung des Eigentums von „Der Titel”`

Given the above, I assume the German yaml files can be updated to produce the desired quote characters without resorting programming. I'm not sure how the internationalization files are updated, but we could either change this ticket to do the updates for all quotes in the German yaml translation files, or a new ticket could be opened to review and do the updates (which may need more than the quote punctuations updated).

Note: Unicode translations were found here: https://www.quackit.com/character_sets/unicode/general_punctuation_unicode_character_codes.cfm

**Comment by jmfrenzel** [comment] 2019-05-23 15:25
@fritzfreiheit  since hyrax will deliver utf-8 what if in the yaml we explicitly use "„ " and "“" ? This would more convenient to maintain. Could you test this? I don't have a dev instance at hand.

**Comment by fritzfreiheit** [comment] 2019-05-23 15:35
@jmfrenzel -- Yes, I just tried it on my development instance of Hyrax, and the explicit use of utf-8 characters worked.

**Closed** 2019-05-23 18:02 UTC
Labels: bug, priority

**Comment by kellyChex** [comment] 2019-07-10 06:19
<img width="995" alt="Screen Shot 2019-07-09 at 11 12 26 PM" src="https://user-images.githubusercontent.com/9621070/60945042-5b7e1480-a29f-11e9-97b9-4233d8f2d329.png">

Confirmed the quotations are showing
