### ISSUE TITLE
Upload from dropbox is not working 

### ISSUE THREAD

**Issue by julesies** [samvera/hyrax#1852] opened 2017-10-11 16:51 UTC
### Descriptive summary

Upload from cloud via Dropbox is not working due to dropbox dropping support for the APIv1.

See ticket from @awead for description https://github.com/samvera/browse-everything/issues/159

**Comment by jrgriffiniii** [comment] 2018-11-15 15:19
I don't believe so, I was not able to reproduce the issue locally.

**Comment by jrgriffiniii** [comment] 2018-11-15 15:45
Apologies, I was incorrect, there were some issues I identified some weeks ago.  They don't directly affect just the Dropbox provider however, please see:

https://github.com/samvera/hyrax/compare/master...jrgriffiniii:browse-everything-1.0.0-update

I can test against earlier releases of browse-everything, and shape these changes into a PR (which, I suspect, might be best scoped for #2804).

**Comment by no-reply** [comment] 2019-09-23 19:24
I'm still pretty vague on the status of this ticket. Should this have been fixed upstream?

**Comment by rjkati** [comment] 2021-01-28 19:27
"Add cloud files" in Hyrax 3.0.0 rc3 does not list Dropbox as an option. Only Box is listed.
![box](https://user-images.githubusercontent.com/32644254/106188103-89be9000-6174-11eb-8890-6e6cd98b22f8.PNG)

@jlhardes seems like we can close this ticket.

**Comment by jlhardes** [comment] 2021-02-04 14:52
It looks like things have been addressed in Browse Everything and that nurax-dev is not configured to connect to Dropbox (only Box) so a Dropbox connection is not testable there. Is anyone able to test and verify via local install that connecting to Dropbox works? @jeremyf or @dlpierce or @crisr15 - I don't even have a Dropbox account anymore.

**Closed** 2021-03-29 17:04 UTC
Labels: bug
