### ISSUE TITLE
FAILING TEST: Collection CRUD refactor - test 'removes all works' fails

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1488] opened 2017-08-14 15:20 UTC
**Priority LOW**

![warning_24](https://cloud.githubusercontent.com/assets/6855473/13064699/3f12e116-d423-11e5-8fce-34d5f360ad41.png) WARNING: This issue may become irrelevant.  The rework of the UI for new/edit changes the way that works and sub-collections are managed.  See related works below.

### Descriptive summary

As part of the [CRUD refactor for collections](https://github.com/samvera/hyrax/issues/1380), the checkbox for select all works does not appear on `/dashboard/collections/:id/edit`.

### Rationale

Collection CRUD was refactored to move CRUD code under the dashboard directory.  Not all functionality for that is back up and running properly.  The bulk of the functionality is working, so to allow others to move their work forward, this was committed as part of PR #TBA.

This issue describes one of the residual problems.

### Expected behavior

When visiting `/dashboard/collections/:id/edit` which runs [app/views/hyrax/dashboard/collections/edit.html.erb](https://github.com/samvera/hyrax/blob/collections-sprint/app/views/hyrax/dashboard/collections/edit.html.erb), it should include checkboxes for each work and a checkbox at the top of the list of works for selecting all works.  It does in the UI, but the [test](https://github.com/samvera/hyrax/blob/collections-sprint/spec/features/dashboard/collection_spec.rb#L252-L259) does not find the `check_all` checkbox.

### Actual behavior

There are no checkboxes for bulk updates to works when editing a collection.

### Steps to reproduce the behavior

1. login
1. create 2 works
1. add the works to the collection via Dashboard -> Works -> select all -> Add to Collection ->  New Collection -> name collection and save
1. navigate to Dashboard -> Collections -> select Edit from action menu of collection with 2 works

Should show works at the bottom and should have check boxes beside each and one at the top of the works section to select all.

### Related work

#1380 Adjust routes to accommodate a public landing page and permission templates
#1417 Collections: Update UI for index views (All/Your) of MVC for Managing Collections
#1427 Collections: Create an admin show view
#1428 Collections: Update public landing page to include branding and other UI recommendations

**Comment by mcdowney** [comment] 2019-09-26 15:42
Unable to reproduce; Collections UI has changed since this ticket was written. Closing for now

**Closed by mcdowney** 2019-09-26 15:42 UTC
Labels: bug, collections/admin sets, user interface
