### ISSUE TITLE
Administrative Sets button on dashboard raises exception

### ISSUE THREAD

**Issue by bess** [samvera/hyrax#2396] opened 2017-12-18 17:48 UTC
### Descriptive summary

When the `Administrative Sets` button on the admin dashboard is pressed, it raises an uncaught exception: 
`ActionView::Template::Error: undefined method `flatten' for nil:NilClass`. This resolves to an error in `app/views/hyrax/admin_sets/index.html.erb:30`
```ruby
<td><%= safe_join(admin_set.creator) %></td>
```

On Hyrax 2 head, the default admin set does not have a `creator`. See https://github.com/samvera/hyrax/blob/de29ce00eef1e6532a286181754f131942b00c77/app/services/hyrax/admin_set_create_service.rb#L18. 
The problem can be fixed by changing this line like this:

```ruby
<td><%= safe_join(admin_set.creator || [""]) %></td>
```

Or it could be fixed by ensuring the default admin set has a `creator`.

**Comment by elrayle** [comment] 2018-01-30 16:06
@bess, what are the steps to reproduce this bug?  I'm not sure what button you are pressing.

**Comment by vantuyls** [comment] 2019-03-15 19:25
admin dashboard no longer has an "admin sets" button due to UI changes. closing issue.

**Closed by vantuyls** 2019-03-15 19:25 UTC
Labels: Effort: Minor, bug, collections/admin sets
