### ISSUE TITLE
solr can't Run

### ISSUE THREAD

**Issue by rodyoukai** [samvera/hyrax#1392] opened 2017-07-25 20:40 UTC
Hi everyone:

In a clean installation i have this error to try execute solr_wrapper:

Faraday::ConnectionFailed: execution expired
/home/rod/hyrax-demo/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_h                                                                                                             ttp.rb:78:in `perform_request'
/home/rod/hyrax-demo/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_h                                                                                                             ttp.rb:38:in `block in call'

Yesterday solr ran correctly, but now i have this issue...

**Comment by mjgiarlo** [comment] 2017-07-25 20:43
@rodyoukai Do you get that error when you start `solr_wrapper`, or at some other point? Can you include a snippet from your terminal/console, or a fuller backtrace, and more information about how we might reproduce this error? Thanks for reporting this!

**Comment by rodyoukai** [comment] 2017-07-25 21:13
I try create a new app with this command

> rails _5.0.3_ new my_app -m https://raw.githubusercontent.com/samvera/hyrax/master/template.rb

All finishe correctly and now run:

> bin/rails hydra:server

Yesterday I use those commands with any error and deploy a Hyrax App with any problem...

This is the full trace:

> rod@ubuntu-512mb-nyc3-01:~/hyrax$ rails hydra:server --trace
** Invoke hydra:server (first_time)
** Execute hydra:server
rails aborted!
Faraday::ConnectionFailed: execution expired
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `initialize'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `open'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `block in con                                                                                                             nect'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:78:in `perform_request'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:38:in `block in call'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:85:in `with_net_http_connection'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:33:in `call'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/request/url_encode                                                                                                             d.rb:15:in `call'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:14                                                                                                             1:in `build_response'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/connection.rb:386:                                                                                                             in `run_request'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/connection.rb:149:                                                                                                             in `get'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday.rb:100:in `method_                                                                                                             missing'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/configura                                                                                                             tion.rb:159:in `fetch_latest_version'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/configura                                                                                                             tion.rb:85:in `version'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:135:in `archive_download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:131:in `rescue in default_download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:129:in `default_download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:64:in `download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:107:in `default_solr_zip_path'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:69:in `solr_zip_path'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:297:in `download'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:259:in `extract'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:248:in `extract_and_configure'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:63:in `wrap'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper.rb:43:in                                                                                                              `wrap'
/home/rod/hyrax/vendor/bundle/gems/active-fedora-11.4.0/lib/active_fedora/rake_s                                                                                                             upport.rb:17:in `with_server'
/home/rod/hyrax/vendor/bundle/gems/hydra-core-10.5.0/lib/tasks/hydra.rake:6:in `                                                                                                             block (2 levels) in <top (required)>'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in                                                                                                              execute'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in                                                                                                              invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchroni                                                                                                             ze'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_w                                                                                                             ith_call_chain'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:152:in `i                                                                                                             nvoke_task'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `b                                                                                                             lock (2 levels) in top_level'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `e                                                                                                             ach'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `b                                                                                                             lock in top_level'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:117:in `r                                                                                                             un_with_threads'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:102:in `t                                                                                                             op_level'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/commands/rake/rake_c                                                                                                             ommand.rb:21:in `block in perform'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:178:in `s                                                                                                             tandard_exception_handling'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/commands/rake/rake_c                                                                                                             ommand.rb:18:in `perform'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/command.rb:46:in `in                                                                                                             voke'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<                                                                                                             top (required)>'
/home/rod/hyrax/bin/rails:9:in `require'
/home/rod/hyrax/bin/rails:9:in `<top (required)>'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in                                                                                                              `load'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in                                                                                                              `call'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client/command.rb:7:i                                                                                                             n `call'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/bin/spring:49:in `<top (required                                                                                                             )>'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `loa                                                                                                             d'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<to                                                                                                             p (required)>'
/home/rod/hyrax/bin/spring:15:in `require'
/home/rod/hyrax/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Net::OpenTimeout: execution expired
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `initialize'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `open'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:904:in `block in con                                                                                                             nect'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:78:in `perform_request'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:38:in `block in call'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:85:in `with_net_http_connection'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/adapter/net_http.r                                                                                                             b:33:in `call'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/request/url_encode                                                                                                             d.rb:15:in `call'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:14                                                                                                             1:in `build_response'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/connection.rb:386:                                                                                                             in `run_request'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday/connection.rb:149:                                                                                                             in `get'
/home/rod/hyrax/vendor/bundle/gems/faraday-0.12.2/lib/faraday.rb:100:in `method_                                                                                                             missing'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/configura                                                                                                             tion.rb:159:in `fetch_latest_version'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/configura                                                                                                             tion.rb:85:in `version'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:135:in `archive_download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:131:in `rescue in default_download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:129:in `default_download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:64:in `download_url'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:107:in `default_solr_zip_path'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/settings.                                                                                                             rb:69:in `solr_zip_path'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:297:in `download'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:259:in `extract'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:248:in `extract_and_configure'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper/instance.                                                                                                             rb:63:in `wrap'
/home/rod/hyrax/vendor/bundle/gems/solr_wrapper-1.1.0/lib/solr_wrapper.rb:43:in                                                                                                              `wrap'
/home/rod/hyrax/vendor/bundle/gems/active-fedora-11.4.0/lib/active_fedora/rake_s                                                                                                             upport.rb:17:in `with_server'
/home/rod/hyrax/vendor/bundle/gems/hydra-core-10.5.0/lib/tasks/hydra.rake:6:in `                                                                                                             block (2 levels) in <top (required)>'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in                                                                                                              execute'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in                                                                                                              invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchroni                                                                                                             ze'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_w                                                                                                             ith_call_chain'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:152:in `i                                                                                                             nvoke_task'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `b                                                                                                             lock (2 levels) in top_level'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `e                                                                                                             ach'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `b                                                                                                             lock in top_level'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:117:in `r                                                                                                             un_with_threads'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:102:in `t                                                                                                             op_level'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/commands/rake/rake_c                                                                                                             ommand.rb:21:in `block in perform'
/home/rod/hyrax/vendor/bundle/gems/rake-12.0.0/lib/rake/application.rb:178:in `s                                                                                                             tandard_exception_handling'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/commands/rake/rake_c                                                                                                             ommand.rb:18:in `perform'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/command.rb:46:in `in                                                                                                             voke'
/home/rod/hyrax/vendor/bundle/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<                                                                                                             top (required)>'
/home/rod/hyrax/bin/rails:9:in `require'
/home/rod/hyrax/bin/rails:9:in `<top (required)>'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in                                                                                                              `load'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in                                                                                                              `call'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client/command.rb:7:i                                                                                                             n `call'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/bin/spring:49:in `<top (required                                                                                                             )>'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `loa                                                                                                             d'
/home/rod/hyrax/vendor/bundle/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<to                                                                                                             p (required)>'
/home/rod/hyrax/bin/spring:15:in `require'
/home/rod/hyrax/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => hydra:server

**Comment by mjgiarlo** [comment] 2017-07-25 21:17
@rodyoukai Looking over the traceback, `solr_wrapper` runs the following code:

https://github.com/cbeer/solr_wrapper/blob/v1.1.0/lib/solr_wrapper/configuration.rb#L159

Which deferences the following URI to get the latest version of Solr:

https://svn.apache.org/repos/asf/lucene/cms/trunk/content/latestversion.mdtext

Can you hit that URL from your machine? Is there some reason you wouldn't be able to do that now, like outbound firewalling?

Any other ideas, @cbeer? I don't believe this is an issue with Hyrax proper.

**Comment by rodyoukai** [comment] 2017-07-25 21:28
Hi @mjgiarlo, thanks for your time, I continue:

I try and obtain this:


rod@ubuntu-512mb-nyc3-01:~$ wget https://svn.apache.org/repos/asf/lucene/cms/trunk/content/latestversion.mdtext
--2017-07-25 17:24:12--  https://svn.apache.org/repos/asf/lucene/cms/trunk/content/latestversion.mdtext
Resolving svn.apache.org (svn.apache.org)... 209.188.14.144
Connecting to svn.apache.org (svn.apache.org)|209.188.14.144|:443... failed: Connection timed out.
Retrying.

Mi machine is a Droplet from DigitlaOcena, if I use my browser in my personal machine y obtain a white page whit this text:

6.6.0

**Comment by mjgiarlo** [comment] 2017-07-25 22:04
That could be it, @rodyoukai. Can you access your droplet in a way that would permit you to test that hypothesis? You may also want to follow up directly with DigitalOcean. I'm closing this issue for now since it's not one we can fix within the Hyrax codebase, but feel free to drop comments here if I can do anything to assist.

**Closed by mjgiarlo** 2017-07-25 22:04 UTC
Labels: feedback needed

**Comment by rodyoukai** [comment] 2017-07-25 22:09
Thanks for your help @mjgiarlo, you Rock ;)

**Comment by SykesStudio** [comment] 2017-09-27 19:01
Hello, I keep getting this error, Any suggestions? 

Starting Solr 7.0.0 on port 8983 ... /home/SolrUser/.rvm/gems/ruby-2.4.0/gems/solr_wrapper-1.1.0/lib/solr_wrapper/popen_runner.rb:6:in `popen': Permission denied - /tmp/solr-7.0.0/bin/solr (Errno::EACCES)

**Comment by mjgiarlo** [comment] 2017-09-27 20:30
@SykesStudio Yep! See here: https://github.com/samvera/hyrax/issues/1727#issuecomment-332608216
