### ISSUE TITLE
direct links to works, filesets, and analytics pages have no breadcrumbs

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#3385] opened 2018-11-07 17:11 UTC
### Descriptive summary

if one drops a link directly to a work showpage, fileset showpage, or analytics showpage, there are no breadcrumbs, which make it impossible to contextualize and navigate the relationships among these views. Providing breadcrumbs or some other navigation will help users navigate. 

### Expected behavior
some kind of navaigation capability from these pages to their related pages (eg. the work for which analytics are being displayed, the work the fileset is part of)

### Actual behavior
from a direct link, there is no navigation interface

### Steps to reproduce the behavior

1. go to a work
2. go to the analytics page for the work
3. see breadcrumbs
4. go to a work
4b. go to the work's analytics page
5. copy the URL for the analytics page
6. open a new browser tab
7. paste in URL
8. see no breadcrumbs

**Comment by adamjarling** [comment] 2018-11-08 16:41
@vantuyls This has to do with the `breadcrumbs_for_...` builders in the controllers I think.  If someone is more familiar with that part of the app or Ruby, might be better suited for it than I.

**Comment by no-reply** [comment] 2018-11-12 20:32
I think this is by design? Since this view (like others) is accessible from various contexts, the breadcrumbs should provide the user a trail back through the path they came from. If they dropped a link in, which set of breadcrumbs should we display?

I'm honestly a bit confused about how the `dashboard` breadcrumb finds its way in when I find a work from the catalog.

**Comment by blancoj** [comment] 2019-08-15 19:05
@no-reply  we actually flagged this as an issue in our local instance and made the change.  I will put in a PR with our change, it is pretty straight forward.

**Comment by dlim87** [comment] 2019-09-10 21:19
It is now retaining the breadcrumbs (except for "return to search results", which is expected to be dropped) when the URL is c/p from the work show page, file show page, or analytics page. 

However, there was some weird behavior with the breadcrumbs. Like was noted earlier in this ticket, it adds in "Dashboard" to the breadcrumbs, even when you're navigating from elsewhere.

**Comment by fritzfreiheit** [comment] 2019-11-05 17:09
I've tested this on my local host and it appears to be behaving correctly.

**Comment by dlim87** [comment] 2019-11-05 23:44
I'm not really sure what the movement in this ticket was for, it doesn't appear like any action was taken? It still has the same behaviors as a couple months ago: the breadcrumbs _are_ displaying even when following a direct work.

It just says Home / work-name if you're a guest or Home / Dashboard / Works / work-name if you're logged in.

**Comment by no-reply** [comment] 2019-11-06 00:03
it seems to me like there's still wild disagreement about what the correct behavior is, re: https://github.com/samvera/hyrax/issues/3385#issuecomment-438019081

to be clear: breadcrumbs *SHOULD NOT* display when the user has not browsed in the application. breadcrumbs contextualize the user's session, and are not fixed for a given page. 

if the work on this has moved us away from that behavior, we should revert it.

thanks for your vigilance on this @dlim87.

**Comment by fritzfreiheit** [comment] 2019-11-06 13:58
Thanks for the clarification. I misinterpreted the requirement.

**Comment by fritzfreiheit** [comment] 2019-11-06 17:47
@samvera/hyrax -- @no-reply has asked me to make a general request to comment and verify the expected behavior for breadcrumbs to NOT be displayed when a hyrax collection, work, file set, etc. page is navigated to from an external web site or without a referrer, that is, that breadcrumbs are only displayed for navigation internal to the website. -- Thanks!

**Comment by no-reply** [comment] 2019-11-06 17:59
cc: @samvera/hyrax-repo-managers @samvera/hyrax-ui-ux-advisors

**Comment by no-reply** [comment] 2020-09-04 17:48
closing this as not in need of further rework.

we're satisfied with the current breadcrumb behavior.

**Closed** 2020-09-04 17:49 UTC
Labels: user interface

**Comment by MariaStarPower** [comment] 2020-09-09 23:49
The **breadcrumbs** are present when navigating to a page internally and also when copying and pasting a link to that page in another tab.

Analytics graph:

<details>

Breadcrumbs are present when navigating to the Analytics graph from inside of a work:

<img width="1478" alt="Image 2020-09-09 at 4 31 07 PM" src="https://user-images.githubusercontent.com/32848057/92664834-e8fd3000-f2b9-11ea-86a6-5c4cd402516c.png">

Copied the URL from the work's Analytics graph page and pasted it into a new tab:

<img width="1360" alt="Image 2020-09-09 at 4 34 34 PM" src="https://user-images.githubusercontent.com/32848057/92665078-7a6ca200-f2ba-11ea-8b72-1b0c6ebe10ee.png">

Breadcrumbs are still present on the Analytics graph page in the new tab:

<img width="1481" alt="Image 2020-09-09 at 4 35 51 PM" src="https://user-images.githubusercontent.com/32848057/92665109-92dcbc80-f2ba-11ea-836f-609e009e499c.png">

</details>

Work show page:

<details>

Breadcrumbs are present when navigating internally to a work's show page:

<img width="1476" alt="Image 2020-09-09 at 4 37 41 PM" src="https://user-images.githubusercontent.com/32848057/92665229-dcc5a280-f2ba-11ea-9fba-788c8edda10d.png">

Copied and pasted the link to the work's show page into a new tab:

<img width="1378" alt="Image 2020-09-09 at 4 38 55 PM" src="https://user-images.githubusercontent.com/32848057/92665290-07176000-f2bb-11ea-998b-78d52e6614d4.png">

Breadcrumbs are still present on the work's show page in the new tab:

<img width="1480" alt="Image 2020-09-09 at 4 39 48 PM" src="https://user-images.githubusercontent.com/32848057/92665341-26ae8880-f2bb-11ea-9a84-3984e8fbbf79.png">

</details>

Fileset:

<details>

Breadcrumbs are present when navigating internally to a work's fileset:

<img width="1481" alt="Image 2020-09-09 at 4 41 02 PM" src="https://user-images.githubusercontent.com/32848057/92665392-4b0a6500-f2bb-11ea-9674-05895c12a4f9.png">

Copied and pasted the link to the fileset's page in a new tab:

<img width="1388" alt="Image 2020-09-09 at 4 42 37 PM" src="https://user-images.githubusercontent.com/32848057/92665485-8a38b600-f2bb-11ea-8312-390bcefb8172.png">

Breadcrumbs are still present on the fileset's page in the new tab:

<img width="1477" alt="Image 2020-09-09 at 4 43 52 PM" src="https://user-images.githubusercontent.com/32848057/92665535-b05e5600-f2bb-11ea-95fe-aaa429982c89.png">

</details>

**Comment by MariaStarPower** [comment] 2020-09-09 23:58
As a user who is _not logged in_, I can see **breadcrumbs** leading back to the search results and Home page.

<details>

Show page of a work for a non logged-in user:

<img width="1476" alt="Image 2020-09-09 at 4 53 36 PM" src="https://user-images.githubusercontent.com/32848057/92666073-17c8d580-f2bd-11ea-8f7b-a8a52e3bfb22.png">

Copied and pasted the link to the work's show page into another tab:

<img width="1344" alt="Image 2020-09-09 at 4 55 00 PM" src="https://user-images.githubusercontent.com/32848057/92666124-4050cf80-f2bd-11ea-99ba-b05d390d0ba7.png">

In the new tab, the breadcrumbs just lead back to Home:

<img width="1477" alt="Image 2020-09-09 at 4 56 08 PM" src="https://user-images.githubusercontent.com/32848057/92666206-74c48b80-f2bd-11ea-98f8-b3a924ae6667.png">

</details>
