### ISSUE TITLE
Sharing a work with admin or registered groups when creating a work causes fatal error

### ISSUE THREAD

**Issue by svanschuyver** [samvera/hyrax#3805] opened 2019-05-29 19:44 UTC
### Descriptive summary

Hyrax 2.5.1

### Rationale

When a user tries to share a work they are in the process of creating with a group, the creation of the work fails.

### Expected behavior

Work saves as normal

### Actual behavior

Fatal error occurs. From the log: `Runtime Error (no agent)`

### Steps to reproduce the behavior

1. Begin creating a work
2. On the sharing tab, add admin or registered groups to the work with edit access
3. Click save

### Related work

Link to related tickets or prior related work here.

**Comment by blancoj** [comment] 2019-08-09 18:52
@samvera/hyrax-repo-managers In looking at this, I noticed that if I use the mediated workflow, you never see the Sharing tab for a work - not while the work under 
review, or even after it has been approved.  But with the default workflow it is always available.  This seems odd.

Also, I noticed that once a work is created using the default workflow, the sharing functionality works fine.  I'm wondering what the user story for this is.  Perhaps sharing should only be available after the work is created?

**Comment by julesies** [comment] 2019-08-12 14:02
@blancoj  there are quite a few tickets related to this issue. In general the consensus was that the sharing tab should be hidden from depositors (think student deposits), but in reality it has some issues. https://github.com/samvera/hyrax/issues/3175 and https://github.com/samvera/hyrax/issues/3166 

This bug however, could be on the default workflow? This is difficult to reproduce on Nurax since groups are not actually enabled. We will try it locally.

**Comment by julesies** [comment] 2019-08-12 14:09
@blancoj @svanschuyver we reproduced this bug in the following ways
1. Add a work in a default workflow, add "registered" group to the work, and hit save, you get the rails error
2. Add a work in a default workflow, add a "custom group" to the work, and hit save, it works
2. Add a work in a mediated deposit, add any group to the work, hit save, you get an error

**Comment by blancoj** [comment] 2019-08-15 16:50
@no-reply What I am finding is that when this line of code is executed:
https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/base_actor.rb#L71

you get the `RuntimeError - no agent`

I think this may be related to what @laritakr  posted here:
https://github.com/samvera/hyrax/issues/3274

If you create a work without any sharing info, it works fine, and if you then go back and add the sharing info, there are no errors generated.

**Comment by jeremyf** [comment] 2020-09-03 14:59
I have tried to duplicate this error, but have been unable to do so.

I believe there is an extremely complicated application/data state that is required to exist to reproduce this error.

What I did was:

1) Start a clean build of Hyrax (using the venerable .internal_test_app)
2) I followed the steps here https://github.com/samvera/hyrax/wiki/Hyrax-Development-Guide#work-with-test-app-in-the-browser
3) I registered as a new user (which because of the role_map.yml) meant I was an admin
4) I went to http://localhost:3000/concern/generic_works/new and attempted to follow the Aug 12, 2019 steps from @julesies . I did not see a "registered" group.  So I was unable to do that.  I did select a group, and things worked.

I don't know what steps I would need to take to duplicate the mediated deposit step.

@crisr15, please advise.

**Comment by jeremyf** [comment] 2020-09-03 17:12
This appears to relate to #3974, which passed QA.  I'm closing this issue as its not something I can reproduce, and the raised error (e.g. `no agent`) no longer exists in the code-base.

**Closed by jeremyf** 2020-09-03 17:12 UTC
Labels: bug, needs reproduction
