### ISSUE TITLE
Translation Missing Error

### ISSUE THREAD

**Issue by svanschuyver** [samvera/hyrax#3773] opened 2019-05-09 14:01 UTC
### Descriptive summary

Hyrax 2.5.0

### Rationale

When generating the default admin set in Hyrax 2.5.0, the admin set name throws a translation missing error: `translation missing: en.hyrax.collection_type.admin_set_title`

### Expected behavior

Generating a default admin set will not throw any errors, and translate into all hyrax default languages

### Steps to reproduce the behavior

1. Build a new hyrax 2.5.0 app
2. Generate default admin set using `RAILS_ENV=production rake hyrax:default_admin_set:create`
3. View Collection Type and view error

### Related work

Other related missing translation errors fixed in https://github.com/samvera/hyrax/pull/3763

**Comment by no-reply** [comment] 2019-05-14 16:53
This is related to https://github.com/samvera/hyrax/issues/3136

**Comment by no-reply** [comment] 2019-05-14 16:53
Could somebody consider documenting the known workaround, here?

**Comment by svanschuyver** [comment] 2019-05-22 17:15
https://github.com/curationexperts/laevigata/pull/1250
https://github.com/UCLALibrary/californica/blob/master/lib/tasks/fix_collection_type_labels.rake

**Comment by no-reply** [comment] 2019-05-30 21:11
Closing this as duplicate of #3136.

The Laevigata fix above is also linked from that ticket.

**Closed by no-reply** 2019-05-30 21:11 UTC
Labels: bug

**Comment by scherztc** [comment] 2019-08-14 17:58
This is affecting some of my application test  in our scholar code

spec/features/hyrax/collection_type_spec.rb
spec/features/hyrax/dashboard/collection_spec.rb

Any work arounds for this in a testing environment?
