### ISSUE TITLE
Extract graphviz utility from Hyku for workflows

### ISSUE THREAD

**Issue by jeremyf** [samvera/hyrax#2865] opened 2018-03-29 20:48 UTC
At present, there is a tool for visualizing workflows built in Hyku (see https://github.com/samvera-labs/hyku/commit/928da1e0074362b535e70a18b67d87ecccecb9be)

**Comment by no-reply** [comment] 2018-07-02 19:42
This is a duplicate of #226.

**Closed by no-reply** 2018-07-02 19:42 UTC
Labels: documentation, duplicate, workflow
