### ISSUE TITLE
Universal Viewer layout issues (Bootstrap 4)

### ISSUE THREAD

**Issue by eporter23** [samvera/hyrax#5679] opened 2022-06-13 20:50 UTC
### Descriptive summary

In the Hyrax 3.x Bootstrap 4 branches, there are some layout issues in the Universal Viewer's Contents and Downloads panels.

### Rationale

We should maintain design continuity wherever possible and also make sure text labels are easy to read.

### Expected behavior

In the Contents pane, thumbnails are typically listed "2-up" and their fileset label is displayed below the image.
In the Downloads options panel, the names of any files set in the Edit Work > Rendering Options (additional downloadable files for the work) should be easy to read.

<img width="283" alt="Screen Shot 2022-06-13 at 4 43 53 PM" src="https://user-images.githubusercontent.com/13855987/173442054-f89b54ea-aa38-4570-ba81-0128ec245b7f.png">

<img width="250" alt="Screen Shot 2022-06-13 at 4 49 25 PM" src="https://user-images.githubusercontent.com/13855987/173442904-45066aa9-409f-4334-9c1b-0e8ed66e73bc.png">

### Actual behavior
Thumbnails are listed in a single column and the fileset label is displayed to the right of the image.

<img width="466" alt="Screen Shot 2022-06-13 at 4 44 45 PM" src="https://user-images.githubusercontent.com/13855987/173442170-28469fee-0f0a-46d1-9a0c-5351236fd5cf.png">

Download Whole Resource option: filenames don't have enough spacing or margins from the label:
<img width="322" alt="Screen Shot 2022-06-13 at 4 46 15 PM" src="https://user-images.githubusercontent.com/13855987/173442387-725d241c-3334-4362-b427-f88d87b18ae4.png">

### Steps to reproduce the behavior

1. Create or navigate to a work with more than one image-based fileset attached which also has an additional downloadable file provided in the manifest
2. View (expand if needed) the Contents pane and see the thumbnail layout
3. Click on the Downloads option and see the layout of the filename relative to the Download Whole Resource label.

### Related work

Link to related tickets or prior related work here.

**Comment by mathewjordan** [comment] 2022-06-14 18:28
@eporter23 I'm having trouble getting UV to display on a Work. This might just me not enabled something correctly. Can you let me know how I'd best enable UV?

**Comment by mathewjordan** [comment] 2022-06-15 19:46
@eporter23 do you know of a nurax build where UV is rendering on a generic work? I'd like to compare class structure on these.

**Comment by eporter23** [comment] 2022-06-15 19:48
This one is kind of working, but isn't showing a thumbnail in the sidebar: https://nurax-dev.curationexperts.com/concern/images/cr56n121g?locale=en

**Comment by eporter23** [comment] 2022-06-15 19:50
Here's another one that is partially working: https://nurax-dev.curationexperts.com/concern/generic_works/ht24wj68c?locale=en

**Comment by mathewjordan** [comment] 2022-06-16 18:08
@eporter23 

Been looking at this for a bit an I'm wondering if this is related to the UV update completed a few months back https://github.com/samvera/hyrax/commit/8c35e23d7866da435c04c9da7c0388220a153fe8#diff-4cff8870450b27ebc38fb23c7a271e6aefe524f043b426f669313d11a5cf8761R6

Previous to our update, hyrax used a version of 3.0.16 which is about 4 years old.  That version seemed to do 2col by default. More recent versions of UV, including 3.1.4 do 1col by default. Though, I cannot find the exact version that this changed (seems like it's 3.1.x), I believe this is by design to not be assumptive of viewing behavior.

I wonder if the UV update is a change that should occur in a different hyrax release? 4.x has now been released as well so perhaps this is a good time to investigate if a move from 3 -> 4 is appropriate.

**Comment by mathewjordan** [comment] 2022-06-16 21:29
To be more clear @eporter23, I ebelieve this issue should be closed. If the layout of the content area in UV is still considered a problem, we should probably revert to an early version of UV `3.0.x`, consider how we could write IIIF manifests using the 2.x spec to use `viewingHint`,  OR be okay with the current rendering using 1col.

**Comment by eporter23** [comment] 2022-06-17 13:24
@mathewjordan I see what you mean. I think 1col is probably okay given those circumstances though I am not sure how well the label/fileset name wraps if it's a long name? I'll do some more checking on that. Also, were you able to address the "Download whole resource" + filename layout? It seems to be missing some punctuation and spacing between the label and the filename.

**Comment by jlhardes** [comment] 2022-06-21 17:51
It looks like that UV version update happened right after Hyrax 3.4.1 was released. I think it is a good idea to update the version of the UV we are using by default but I'm not sure we should mix that in with this BL7/BS4/Rails6 update release unless it is necessary for upgrading one of those pieces. @dlpierce does it present a problem with our upgrade work here to revert the UV back to 3.0.16?

@eporter23 are the changes in how the UV looks making it unusable or broken in Hyrax with UV 3.1.4?

**Comment by rjkati** [comment] 2022-11-02 15:08
This looks resolved in Hyrax 4.0.0.beta2.

Example: https://nurax-dev.curationexperts.com/concern/generic_works/nz805z98f?locale=en

UV contents appear side-by-side with their fileset label displayed below.
![contents](https://user-images.githubusercontent.com/32644254/199523468-9a6fb455-13c9-4615-a3dd-f375cc6b677e.PNG)


The Download option does not include a "whole resource" option in the UV to download the PDF, although the option to download appears in the Item view.
![download_whole_image](https://user-images.githubusercontent.com/32644254/199522441-57482a3a-65f0-4ddf-bbe1-31bb66977f3e.PNG)

**Closed by rjkati** 2022-11-02 15:08 UTC
Labels: bootstrap 4 upgrade dev congress
