### ISSUE TITLE
ES6 breaks JS compression unless Uglifier is in harmony mode

### ISSUE THREAD

**Issue by seanaery** [samvera/hyrax#4705] opened 2021-01-07 20:07 UTC
### Descriptive summary

Version: `2.x.stable`, `2.9.1`

This line of ES6 syntax introduced in #4503 makes `assets:precompile` fail unless one also configures Uglifier to run in "harmony mode":
`let skipTo = '#' + $(this)[0].firstElementChild.hash.split('#')[1];`

Solution in `config/environments/production.rb`:
`config.assets.js_compressor = Uglifier.new(harmony: true)`

### Rationale
Introducing ES6 requires the above change to fix the asset pipeline in production environments. It also adds a requirement for implementers to add a transpiler (e.g. `babel`) for backward compatibility with older browsers like IE.

### Expected behavior
Assets precompile without issue.

### Actual behavior
During an `assets:precompile` task, the following error stops it from completing:
`Uglifier::Error: Unexpected token: name (skipTo). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).`

### Steps to reproduce the behavior

1. Run `rake assets:precompile`

### Related work
- #4503

**Comment by no-reply** [comment] 2021-01-07 23:20
marking this as a bug, since it breaks deployments for Hyrax 2.x applications.

**Comment by no-reply** [comment] 2021-01-07 23:23
marking this `needs reproduction` can this be reproduced in CI? are we running `rake assets:precompile` or equivalent during the build stage for 2.x-stable?

**Closed** 2021-01-08 19:15 UTC
Labels: bug, needs reproduction
