### ISSUE TITLE
As a user I expect to be able to set the thumbnail for a work from the file manager

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2010] opened 2017-10-27 21:42 UTC
Expected behavior

I would expect changing the representative media in the file manager to change the item's thumbnail or to give me the option to also change the thumbnail.

Actual behavior

I can select a representative file in the file manager but this does not change the thumbnail. The option to change the thumbnail is buried 'additional fields' on the metadata edit screen.

**More comments at:**
https://github.com/curationexperts/nurax/issues/112

**Comment by jcoyne** [comment] 2017-10-28 13:02
You should  be able to set both the thumbnail and representative in the file manager.  Can you add a screenshot of what you see? 

https://github.com/samvera/hyrax/blob/master/app/views/hyrax/base/_file_manager_member_resource_options.html.erb#L3

**Comment by jcoyne** [comment] 2017-10-30 13:33
Is this a dup of #2019

**Comment by starsplatter** [comment] 2017-10-30 13:47
This looks like a dupe of the issue to me. I originally reported this. Looking now I am not sure if things changed or if I just misunderstood the UI. I think changing the radio buttons to check boxes would make it clearer that thumbnail and rep media are independent of each other but I think this can get closed with a resolution of 'user confusion'. :)

**Comment by no-reply** [comment] 2018-09-17 19:51
Closing per https://github.com/samvera/hyrax/issues/2010#issuecomment-340448509

**Closed by no-reply** 2018-09-17 19:51 UTC
