### ISSUE TITLE
Allow embargoed works to have discoverability option

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5016] opened 2021-07-07 21:37 UTC
### Descriptive summary

As reported in #140 embargoed works sometimes have a use case to be discoverable even if files are not viewable or downloadable. From @julesies [comment](https://github.com/samvera/hyrax/issues/140#issuecomment-293278762) regarding embargoed content:

"We have a couple of use cases where we would want the "Metadata Only" view.

1. For embargoed works - our Graduate School likes the dissertation metadata to be discoverable even if we can't exposed the files while the work is under embargo. This helps show the output of students and also exposes papers to google where an author might not be able to share their paper with the public but could share with individuals by request.
2. The Honors Theses also wants to use this "Metadata Only" view for honors theses where they want to store the files/papers permanently, but want to expose the metadata. In this case, they never intend to release the papers, for specific reasons."

This is an enhancement. 

It would also be good to know if anyone has implemented anything locally that makes it possible to discover embargoed content?

### Rationale

While this is not always the case for embargoed works, right now there is no option to allow an embargoed work to be discoverable. It does not show in search results as long as the embargo is in effect.

### Proposed behavior

When applying an embargo to a work, there is an option to make the work discoverable. Files are still restricted from being viewable or downloadable (similar to a public work with private files). Can this be an option to set for all works at the collection/admin set level or should it only be available at the individual work level in the Visibility settings?

### Actual behavior

Applying an embargo means the work does not appear in search results for most users. It will appear in search results for the depositor if the depositor is logged in.

### Steps to reproduce the behavior

1. Log in (either as admin or regular logged in user)
2. Create a work with required metadata (unique title so it can be easily searched)
3. Select Embargo under Visibility settings with a date in the future
4. Save and log out
5. Search for that work as a public end user or a different logged in user and it is not discoverable

### Related work

Discussion in #140 brought up this use case.

**Comment by mcdowney** [comment] 2021-07-08 13:48
Duke's workaround is to make the parent work and its metadata public and all files and/or child works private until the embargo period ends. It's kind of a pain, as it's highly manual and relies on calendar reminders, but works for us for now. Would love to see this enhancement eventually!

**Comment by orangewolf** [comment] 2021-08-14 05:46
as @mcdowney suggests, Hyrax does support this - but because of #1134 it is hard to set up.  If you could set the permissions of the individual files when creating a work, you could cover both of these use cases. Once a work is saved with files, editing the permissions on the files does give you this capability. So I think this is a duplicate of #1134

**Comment by jlhardes** [comment] 2021-08-16 20:58
I can remove this if it isn't relevant, but does @cjcolvar's PR WIP #5022 also apply here for setting visibility on files at upload time? I am remembering a demo of this that showed permissions that could be set for each file as it was uploaded.

**Comment by orangewolf** [comment] 2021-08-16 21:04
that makes sense to me, but that's just an opinion. I think the whole system would make more sense to people 5022 got done.

**Comment by rjkati** [comment] 2023-06-15 17:52
Closing as this is possible to do in Hyrax via the aforementioned public work and embargoed/private file workaround. Requested enhancements to make this functionality easier to use are covered in #1134 and #5022

**Closed by rjkati** 2023-06-15 17:52 UTC
Labels: enhancement
