### ISSUE TITLE
Work transfer does not reset edit rights on attached file_sets

### ISSUE THREAD

**Issue by crowesn** [samvera/hyrax#3260] opened 2018-09-11 19:34 UTC
### Descriptive summary

Hyrax v2.1.0

Work transfer does not reset edit rights on attached file_sets when the receiving user opts to remove depositor access.

### Rationale

When removing depositor access at work level, should be removed for attached file sets as well.

### Expected behavior

When transferring a work, the receiving user can choose to remove access original depositor. When they do this the original depositor should not be able to edit the work or the attached file_sets.

### Actual behavior

When the receiving user chooses to remove access from the original depositor, the original depositor is still listed as an edit user of attached file_sets.

### Steps to reproduce the behavior

1. Create a work with a file
1. Transfer it to another user
1. As the other user, accept the request, removing depositor access
1. Check the edit_users on the attached file_sets

### Related work

See this class:

https://github.com/samvera/hyrax/blob/master/app/services/hyrax/change_content_depositor_service.rb

Should this be in the `work.file_sets.each` block?:

```ruby
f.apply_depositor_metadata(user)
f.permissions = [] if reset
f.save!
```

https://github.com/uclibs/ucrate/issues/362

**Comment by crowesn** [comment] 2018-09-12 19:36
Looking over the specs - seems like this behavior might be intentional?

https://github.com/samvera/hyrax/blob/2.0-stable/spec/services/hyrax/change_content_depositor_service_spec.rb#L46

**Comment by crowesn** [comment] 2018-09-12 19:58
> Looking over the specs - seems like this behavior might be intentional?
> 
> https://github.com/samvera/hyrax/blob/2.0-stable/spec/services/hyrax/change_content_depositor_service_spec.rb#L46

Or rather, it could be that [this](https://github.com/samvera/hyrax/blob/2.0-stable/spec/services/hyrax/change_content_depositor_service_spec.rb#L46) `:reset = true` expectation was copied from the non-reset example above and not fully differentiated.

**Comment by rjkati** [comment] 2021-01-28 14:23
Issue still exists in Hyrax 3.0.0 rc3 

@jlhardes, please review since there is discussion of whether this behavior is intentional.

**Comment by jlhardes** [comment] 2021-01-29 17:57
I think this is an oversight and needs to be fixed. If a work is transferred from one user to another user and permissions are reset to remove the first user that first user shouldn't have access to edit anything for that work, which includes the filesets in that work.

**Comment by jeremyf** [comment] 2021-02-05 13:00
First, @crowesn: Thank you for your reported issue. The detail you provided made it very easy to track down and begin engaging the code.

@jlhardes I'm doing some `git` sleuthing.  There's a test that verifies the current (yet unexpected behavior).

Starting with the [change_content_depositor_service_spec.rb](https://github.com/samvera/hyrax/blob/508e7381d9b5cfce4cd27c40406141df47876eca/spec/services/hyrax/change_content_depositor_service_spec.rb#L34:L49), we have a test that asserts the current behavior.

(awead) [introduce the spec in a 2015 commit](https://github.com/samvera/hyrax/commit/468929845f2989913617a297af801bbda6bd8e45), I found this commit by (grosscol) [that subtly removed the expected behavior](https://github.com/samvera/hyrax/commit/0cb55bf46092bbb72c1803e7341074e1ea903a5b#diff-bfac0ce58388b8031096668717616b32e0edbeaf3707ca4cde388ee859dcdd35L20-L24).

So, my analysis is that one commit introduced the bug and a later spec asserted the bug as expected behavior.

**Closed** 2021-02-08 19:47 UTC
Labels: Abilities/Permissions, bug

**Comment by rjkati** [comment] 2021-02-22 20:23
Verified that original depositor is no longer listed on Permissions tab for fileset after work transfer is accepted and original depositor access is removed. The issue has been fixed. @jlhardes
