### ISSUE TITLE
Throwing ActionController::InvalidAuthenticityToken when trying to add works to an existing collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1489] opened 2017-08-14 15:34 UTC
### Descriptive summary

When adding existing works to an existing collection through Dashboard -> Works -> add works to collection, the works are not added and `ActionController::InvalidAuthenticityToken` is thrown.

### Rationale

Collection CRUD was refactored to move CRUD code under the dashboard directory.  Not all functionality for that is back up and running properly.  The bulk of the functionality is working, so to allow others to move their work forward, this was committed as part of PR #TBA.

This issue describes one of the residual problems.

### Expected behavior

When selecting works to add to an existing collection from Dashboard -> Works, the works should be added as members of the collection.

### Actual behavior

* In the UI, `ActionController::InvalidAuthenticityToken` is thrown for existing collections.
* In the UI, if added to a new collection, the works are added correctly.
* In tests, the works are added correctly.

### Steps to reproduce the behavior

1. login
1. create 1 collection
1. create 2 works
1. add the works to the collection via Dashboard -> Works -> select all -> Add to Collection -> select existing collection -> Update Collection

Should show collection show page with 2 works.  Instead, throws `ActionController::InvalidAuthenticityToken`.

### Related work

#1380 Adjust routes to accommodate a public landing page and permission templates
#1417 Collections: Update UI for index views (All/Your) of MVC for Managing Collections
#1427 Collections: Create an admin show view
#1428 Collections: Update public landing page to include branding and other UI recommendations

**Comment by elrayle** [comment] 2017-08-14 23:55
This is not related to the refactor.  I get the same error following the steps to reproduce at master.

**Comment by elrayle** [comment] 2017-08-15 00:34
Adding the following to Hyrax::CollectionsControllerBehavior stops the error, but I'm not sure that is what we want to be doing.

```
module Hyrax
  module CollectionsControllerBehavior
    extend ActiveSupport::Concern
    include Blacklight::AccessControls::Catalog
    include Blacklight::Base

    included do
      skip_before_action :verify_authenticity_token
      # protect_from_forgery prepend: true, with: :exception
      # before_action :authenticate_user!

      before_action :filter_docs_with_read_access!, except: :show
      before_action :remove_select_something_first_flash, except: :show
```

As you can tell from the commented out line, I also tried adding...
* protect_from_forgery - caused the error to happen again when it was or wasn't followed by authenticate_user
* authenticate_user

This is based on recommendations in https://stackoverflow.com/questions/38331496/rails-5-actioncontrollerinvalidauthenticitytoken-error

**Comment by mjgiarlo** [comment] 2017-08-15 16:15
Duplicate of #1191

**Closed** 2017-08-31 15:38 UTC
Labels: bug, duplicate, question
