### ISSUE TITLE
Hyrax::PcdmCollection fails to delete

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#5331] opened 2022-01-21 21:17 UTC
### Descriptive summary

When a collection is created as a Hyrax::PcdmCollection and later deleted, it goes through the process without error, but fails to fully delete.  Viewing Dashboard -> Collections after the delete, the deleted collection is still in the list.

### Rationale

Deleting collections should work whether the collection is an Active Fedora collection or a Valkyrie collection.

### Expected behavior

Deleting a collection deletes the collection and it is no longer listed in Dashboard -> Collections.

### Actual behavior

Deleting a collection goes through all steps and no error was displayed in the UI, but it continues to be listed in Dashboard -> Collections.

_NOTE: Initial debugging appears to show that the collection was deleted from the data store, but not solr.  Need to confirm this._

#### Prerequisites:

Configure Hyrax:
1. Edit `/config/initializers/hyrax.rb` and set:
```
  config.collection_model = "Hyrax::PcdmCollection"
  config.query_index_from_valkyrie = true
  config.index_adapter = :solr_index
```
2. restart rails app
3. Make sure regular `hyrax-development` and `hyrax-valkyrie-dev` solr cores are running .  _Your core names may vary depending on how you start them and how they are configured in the app._
4. Make sure you have access to the datastore (i.e. postgres)

Create Collection
1. click button: New Collection
2. select type: any collection type (except Admin Set)
3. click button: Create Collection
3. set Title: DELETE ME (or other meaningful name)
4. click Save

Verify that the collection was created in both solr cores with `q`:  `title_tesim:DELETE ME` (or similar query).
Verify that the collection and its access control were created in the datastore.

#### To reproduce:

1. navigate to Dashboard -> Collections
2. click drop menu in Actions column beside the collection you created
3. choose: Delete collection
4. click button: Delete
5. navigate to Dashboard -> Collections 

Verify that the collection was deleted from both solr cores with `q`:  `title_tesim:DELETE ME` (or similar query).
Verify that the collection and its access control were created in the datastore.

### Related work

See related issues in Issue #5326 UBER: Hyrax-Valkyrization MVP
See Issue #5407 describing the same issue for Hyrax::AdministrativeSets

**Comment by no-reply** [comment] 2022-01-28 21:58
is this effectively a duplicate of #5407?

**Comment by hackartisan** [comment] 2022-03-01 21:12
Cannot reproduce in nurax-pg or nurax-dev. This appears to be resolved.

**Closed by hackartisan** 2022-03-01 21:12 UTC
Labels: valkyrization
