### ISSUE TITLE
User with Editor role can't see private collection

### ISSUE THREAD

**Issue by VivianChu** [samvera/hyrax#1742] opened 2017-09-28 21:13 UTC
### Descriptive summary

For Hyrax 2.0.0.beta1, User with Editor role can't see a private collection created by other Users.
For Hyrax 2.0.0.alpha, Editor user can see private collection fine.

Hyrax 2.0.0.beta1
![editordashboard](https://user-images.githubusercontent.com/1864660/30990702-1def50d6-a457-11e7-891d-e585fa9563af.png)

![privatecollection](https://user-images.githubusercontent.com/1864660/30990719-28b79a78-a457-11e7-842a-456f86c3e211.png)

For Hyrax 2.0.0.alpha 
![beforeeditordashboard](https://user-images.githubusercontent.com/1864660/30990726-2fb7d914-a457-11e7-9425-2fc7b26e70a3.png)

![beforeprivatecollection](https://user-images.githubusercontent.com/1864660/30990737-382fa37e-a457-11e7-8e05-633b7fcc583d.png)

### Rationale

To have same editor function as previous hyrax version.

### Expected behavior

Editor User can see private collection created by Admin or other Users. 

### Actual behavior

Editor User can't see private collection.

### Steps to reproduce the behavior

1. Log in as admin
2. Create a new collection, select private visibility
3. Log out
4. Log in as editor
5. Go to Dashboard: Collections: All collections
6. Click on a new collection created by admin user
7. Should see message "You are not authorized to access this page"

**Comment by mjgiarlo** [comment] 2017-10-04 20:00
Fixed by https://github.com/samvera/hyrax/pull/1760

**Comment by mjgiarlo** [comment] 2017-10-26 20:54
This only fixed the behavior for administrative users. Reopening.

**Comment by mjgiarlo** [comment] 2017-10-26 20:54
Refs curationexperts/nurax#96

**Comment by elrayle** [comment] 2017-10-27 16:58
### Hyrax 1.0 - 2.0.0.rc1

In Hyrax 2.0, you cannot see collections you did not create through Dashboard -> Collections -> Your Collections.  I am fairly certain that has been the case for all releases (alpha - beta - rc) of Hyrax.  In Sufia, you could see collections shared with you on the 'Shared with me' tab.

In your steps to reproduce, you reference the All Collections tab.  That tab is only shown to admin users.  Perhaps your expectation that this used to work in alpha was because the test was done with an editor who was also an admin user.

### Hyrax collections-sprint branch

In collections-sprint branch, we have added an additional Managed Collections tab to Dashboard -> Collections.  On that tab, you see collections for which you were granted :manage, :deposit, or :view access.  Users will be able to view the admin show page for a collection if they have any of these access levels granted.

**Comment by elrayle** [comment] 2017-10-27 16:58
FYI... works have the same issue where there is no way to see works shared with you through Dashboard -> Works

FYI... There were previous discussions about incorporating Managed Collections and Managed Works into Hyrax 2.0 branch, but the consensus at the time was not to include it as it was too much new work and we were very close to a 2.0 release.  This will be fixed in 2.1 when collections-sprint branch is merged into master.

**Closed** 2017-10-27 18:58 UTC
Labels: blocker, bug, collections/admin sets, in progress
