### ISSUE TITLE
ActionController::InvalidAuthenticityToken when adding a work to a collection

### ISSUE THREAD

**Issue by elrayle** [samvera/hyrax#1362] opened 2017-07-18 14:31 UTC
### Descriptive summary

Adding a work to a collection from Dashboard -> Works -> Your Works, you get ActionController::InvalidAuthenticityToken error after selecting a collection and clicking Update Collection button.

### Expected behavior

The Work becomes a member of the Collection.

### Actual behavior

Error: ActionController::InvalidAuthenticityToken

### Steps to reproduce the behavior

Login: I was logged in as an admin.  I did not test with a non-admin user.
Prep: Need to create 1 collection and 1 work.

1. Click email at right in header and select Dashboard
1. Click Works in Repository Content section
1. Click checkbox beside a work
1. Click Add to Collection button
1. Select a collection and click Update Collection

Error: ActionController::InvalidAuthenticityToken

**Comment by jcoyne** [comment] 2017-07-18 19:43
Duplicate of #1191

**Closed** 2017-07-18 19:44 UTC
Labels: bug
