### ISSUE TITLE
Viewer Access to Admin Set

### ISSUE THREAD

**Issue by vantuyls** [samvera/hyrax#2004] opened 2017-10-27 21:30 UTC
Descriptive summary

Viewers currently have no access to admin sets for which they have been designated a Viewer Role. Here's what seems to be missing:

Notification that they have been added as a Viewer to an Admin Set
Ability to see the Admin Set in the Administrative Sets (/admin/admin_sets) panel
Ability to see pending Works in the Admin Set from the Review Submissions (/admin/workflows) panel
From what I can tell, when a user has been given the Viewer role in an Admin Set, the only thing they are able to do is view a work that is in that Admin Set, pending approval, if they have been given a direct URL. There is no way to navigate to that work, or know that it's there.

Expected behavior

Viewers should be notified when they've been given View access to an Admin Set and should be able to navigate to that Admin Set and take actions on Works in that Admin Set.

Actual behavior

Here is an Admin Set with a Work that is pending approval:
image

Here are the participants of the Admin Set:
image

Here is what the Viewer can see from their Admin Sets panel (note: they can't see the Admin Set they're supposed to View):
image

Here is what they see when the try to view their submissions (note: these are works from admin sets for which the user is a Manager; none of these are from the admin set for which the user is a Viewer):
image

No notifications:
image

The purpose of the Viewer role is not clear to me.

Questions

What am I missing?
Should we add capabilities to the Viewer role?
Should we remove the Viewer role?

**More comments at:**
https://github.com/curationexperts/nurax/issues/121

**Comment by elrayle** [comment] 2017-10-30 19:27
I saw this as well in collections-extensions and was unclear if the inability to view the admin-set was intentional.  What does happen with the viewer role is that when a work is created, the admin-set viewers are given `read-access` to the new work.

@jcoyne @mjgiarlo What is the intended behavior for Viewers of admin-sets?  Can you check which of these you expect to apply.
- [ ] Viewer is assigned `read access` to the admin set
- [ ] Viewer is assigned `read access` to new works
- [ ] Viewer is assigned `reviewer role` to new works that have mediated deposit workflow

FYI... for collections in collection extensions
- [x] Viewer is assigned `read access` to the collection (meaning they see the collection in Dashboard -> Collections -> Managed Collections and can view the collection's admin show page)
- [x] Viewer is assigned `read access` to new works (when created directly in the collection)
- [ ] Viewer is assigned `reviewer role` to new works that have mediated deposit workflow (Collections do not impact workflows, so this is NOT assigned based on a collection)

**Comment by elrayle** [comment] 2017-10-30 19:27
Copied comment by @laritakr from nurax issue https://github.com/curationexperts/nurax/issues/121

My memory of the purpose of the viewer role (based on discussion last fall) was that the Viewer would receive read access to any works created in the admin set after the point in time where they were added as viewer. There was no implied access to the admin set itself at that time, and no retroactive access given to works created prior to the point that the Viewer role was assigned.

This would imply that they need some other way to access the works they are given access to, if the admin set is not the access method.

**Comment by elrayle** [comment] 2017-10-30 19:28
I am working on the documentation for the impact of adding/removing participants for collection types, collections, and admin sets. This should include information on what happens with the workflows, but I don't have that knowledge yet. I'm working with @laritakr to understand the impact. If others have feedback that would also be good to hear.
http://elr37-dev.library.cornell.edu/samvera_docs/collection_extensions_faq_participants.html

**Comment by julesies** [comment] 2017-10-30 21:45
@elrayle are you saying, that we need to test "removing a manager should remove access"? I can have someone do that for roles tomorrow or by Wednesday.

**Comment by elrayle** [comment] 2017-10-31 00:10
I think there is a lack of documentation on the expected impact of participants on works in a workflow, and beyond that to what happens to works in a workflow when a participant is added/removed.  I'm not sure we can come up with a proper solution until we have consensus on what is expected.

**Comment by elrayle** [comment] 2017-11-09 17:06
I have a solution that allows the Viewer to see the admin set index and show pages.  

I'm not convinced this is the problem you are trying to solve.  With the fix in place, the 'reviewer' is still not able to review the work.

To reproduce:
* create two users:  admin and user_B
* Login as admin
* Create admin set AS
* Add viewer to an admin set: Dashboard -> Administrative Sets -> click AS title -> Edit
* Set user_B as a Viewer: Participants -> user: user_B, access: Viewer
* Set workflow to mediated: Workflow -> select mediated
* Give viewer Reviewer role: Dashboard -> Workflow roles -> user: user_B, role: AS approving (mediated)
* Create a work in AS: Dashboard -> Works -> New
   * set required metadata (title: Work 8.11)
   * add file
   * Relationships tab: select AS as the admin set
* Login as user_B
* View admin set: Dashboard -> Administrative Sets -> click AS title

- [ ] Verify that Edit and Delete buttons are not visibility

* Review work: Dashboard -> Review Submissions 

- [ ] Verify Work 8.11 is on the list

* Click Work 8.11 title

<img width="660" alt="image" src="https://user-images.githubusercontent.com/6855473/32618566-bd0c9078-c53d-11e7-9e47-7d227bdb8b36.png">

NOTE: Cannot review!  But should be able to, right?  @julesies  Is this what this issue is really about?

**Comment by elrayle** [comment] 2017-11-09 17:54
I repeated the process and I CAN review.  So I'm guessing maybe I didn't do the steps in order the first time.  Maybe the work was created before the viewer was set.

**Comment by elrayle** [comment] 2017-11-10 13:34
Testing a little further...
Scenario 1: 
* assign user_A 'approving' role only for AdminSet_1
* another user creates a work in AdminSet_1
* user_A can NOT review the new work

Scenario 2:
* grant user_B 'Viewer' access to AdminSet_1
* assign user_B 'approving' role only for AdminSet_1
* another user creates a work in AdminSet_1
* user_B CAN review the new work

Why?  As a Viewer of AdminSet_1, user_B is granted read_access to works created in that admin set.  The user must have read access to the work to be able to review it.

**Comment by julesies** [comment] 2017-11-13 14:56
@elrayle when you say "assign role" where are you doing that? We've been testing review of workflows by adding "manager" to the admin set. I was told that you don't need to assign workflow roles UNLESS you are adding a custom workflow.

**Comment by elrayle** [comment] 2017-11-20 02:26
@julesies When the user was a Viewer, I assigned the approving role by...

* Dashboard -> Configurations -> Workflow Roles
* select User = user_B
* select Role = AdminSet_1 - approving (one_step_mediated_deposit)

**Comment by elrayle** [comment] 2017-11-20 02:28
You don't have to assign roles if the "manager" is doing the approving.  But if a "viewer" is doing the approving, you do have to assign the "approving" role for custom workflows AND for one_step_mediated_deposit.

**Comment by julesies** [comment] 2017-11-20 21:25
ah hmm. Is viewing intended to be a reviewer role? I am trying to think of a why you would not just make them a manager. Do you know?

**Comment by elrayle** [comment] 2017-12-05 10:55
I think some sites see reviewers as power users or users with more responsibility, in which case you would want them to be managers.  But this is not a requirement.  Sites can set any user as a reviewer.  Minimally, a user who will be a reviewer needs to be a Viewer with read access.

**Comment by mjgiarlo** [comment] 2017-12-05 16:10
(FWIW, our original designs for the Admin Set participants did include a distinct role for reviewers in addition to viewers, depositors, and managers.)

**Comment by julesies** [comment] 2017-12-05 16:36
I think reviewers in dig coll workflows are more about reviewing lots of content accuracy (of say a student staff's work) and generally it's okay for them to have manager-type permissions (broadly to a whole collection), which is pretty diff than reviewing for an IR - which is more where a non-library staff has to review a small sub-set of works (and only those) in a given collection. 

this is why i'm suggesting if this is really a dig coll workflow of reviewer, then manager role is the one you likely want to review for that use case. 

the workflow roles, vs collection roles, vs admin set roles is getting confusing!

**Comment by elrayle** [comment] 2018-02-15 18:54
I think this should be a separate issue, but it is related to this discussion, so I'm going to float it here first.

As a non-admin user, I want to see all collections on Managed Collections where I am...
* a manager, depositor, or viewer granted individually
* a manager, depositor, or viewer granted through a group other than Public or Registered

As a non-admin user, I want to see all works on Managed Works where I have...
* edit or read access granted individually
* edit or read access granted through a group other than Public or Registered

If we include Public or Registered group, the list gets too long.

@jrr, @vantuyls, @mjgiarlo Do you agree with this?

I would say the same rules apply for Workflow review panel.

**Comment by jrr** [comment] 2018-02-15 18:57
@elrayle you've got the wrong person! I've never heard of Hyrax.

**Comment by elrayle** [comment] 2018-02-15 18:57
@jrr Oops... its jrr in another system.  Thanks for letting me know.

**Comment by julesies** [comment] 2018-02-15 20:50
@elrayle I think it makes sense the way you describe it. If it were to include registered, I think that would be a problem, but since this excludes registered, it means that these people must be specifically added to a collection. In the way it is written here, I can see this working well for both IR and DigColl use cases. I assume for the collections section that it follows that one can also see all works in that collection as well and not just the collection object?

**Comment by no-reply** [comment] 2018-11-12 23:37
Is this issue still live?

**Comment by mcdowney** [comment] 2019-09-26 17:38
Closing.

**Closed by mcdowney** 2019-09-26 17:38 UTC
Labels: Abilities/Permissions
