### ISSUE TITLE
Display bugs in Transfer menu

### ISSUE THREAD

**Issue by mcdowney** [samvera/hyrax#3977] opened 2019-09-12 20:39 UTC
### Descriptive summary

QA Testing for Hyrax
Hyrax Version: 3.0.0.pre.rc1
Hyrax Branch: master
Hyrax Revision: 48ed925940130bcc5e75092c974555f4f1654390
Nurax Version
ENV: production
SHA: 40b47b0d71af1b958e016ebe49212c1740683133
Branch: 2019-09-12-10-00
Updated: 12 Sep 2019 15:00:37

The column headers for the Transfers Sent and Received tables AND the button text to accept the transfer in the Received table don't appear to be rendering properly. This appears to be happening in both Chrome and Firefox on Windows

![transfer_display_bug](https://user-images.githubusercontent.com/13054800/64818972-3cd81a80-d57b-11e9-9f12-b1cc30fa8c88.JPG)

### Rationale
Text should render properly

### Expected behavior
The column headers in each table and button text render in human readable text

### Actual behavior
Translation error? They're currently rendering as t(".title"), etc.

### Steps to reproduce the behavior

1. Sign in as any kind of user
2. Navigate to dashboard
3. Under "Your Activity", select "Transfers"
4. Tables should display incorrectly

### Related work
https://github.com/samvera/hyrax/issues/3972

**Comment by dlpierce** [comment] 2019-09-13 20:36
Duplicate of #3956

**Closed by dlpierce** 2019-09-13 20:36 UTC
Labels: blocker
