### ISSUE TITLE
Landing on home after selecting  Transfer Ownership of Work 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera/hyrax#3438] opened 2018-11-20 16:52 UTC
### Descriptive summary
Firefox / Linux

Hyrax Version: 3.0.0.pre.beta1
Hyrax Branch: master
Hyrax Revision: 892c70712350a5583a51ad4c5cfec000d07b75de

### Rationale

Admins still can transfer work when  this is turned off in admin/features.

### Expected behavior

Admins still can transfer work when  this is turned off in admin/features.
### Actual behavior
clicking Transfer Work lands on nurax home 

### Steps to reproduce the behavior
as admin 
0. turn off transfers in admin/features
1. go to https://nurax-dev.curationexperts.com/dashboard/my/works?locale=en
2. select  Transfer Ownership of Work  from Select field of a work 

### Related work

Link to related tickets or prior related work here.

**Comment by chrisdaaz** [comment] 2018-11-21 20:38
@jmfrenzel would it make more sense if the "transfer ownership of work" option were no longer available when the feature is disabled?

right now, the app will not allow transfers when feature is disabled, but the ui shows the option:

![image](https://user-images.githubusercontent.com/24395592/48867123-caebd600-ed9a-11e8-8996-81a4905052b5.png)

when i click it, i get directed to the home page with an error message:

![image](https://user-images.githubusercontent.com/24395592/48867150-ddfea600-ed9a-11e8-9d93-405a55dd2b32.png)

this is not ideal. perhaps we can make a ticket that removes that option from the ui when the feature is disabled?

**Comment by chrisdaaz** [comment] 2018-11-21 20:45
it appears that i am only able to see the `transfer ownership of work` option when i am logged in as an admin. i just checked as a general user, and this is not the case.

**Comment by jmfrenzel** [comment] 2018-11-22 14:14
> , the app will not allow transfers when feature is disabled, but the ui shows the option:



> @jmfrenzel would it make more sense if the "transfer ownership of work" option were no longer available when the feature is disabled?
> 
> right now, the app will not allow transfers when feature is disabled, but the ui shows the option:
> 
> ![image](https://user-images.githubusercontent.com/24395592/48867123-caebd600-ed9a-11e8-8996-81a4905052b5.png)
> 
> when i click it, i get directed to the home page with an error message:
> 
> ![image](https://user-images.githubusercontent.com/24395592/48867150-ddfea600-ed9a-11e8-9d93-405a55dd2b32.png)
> 
> this is not ideal. perhaps we can make a ticket that removes that option from the ui when the feature is disabled?
This would limit admin functionality, which I would like to have. So I opt for a fix.

**Comment by chrisdaaz** [comment] 2018-11-27 22:18
@jmfrenzel can you try this again on `nurax-dev`? i can't reproduce this with windows / firefox.

**Comment by jmfrenzel** [comment] 2018-11-28 12:43
i can't either, but now nurax is based on a different Hyrax revision:  
Hyrax Version: 3.0.0.pre.beta1  
Hyrax Branch: master   
Hyrax Revision: b6e511d42bb6466c9f2c9b480ca79d2fe60e5453

**Comment by chrisdaaz** [comment] 2018-11-28 15:06
@jmfrenzel thanks for checking (and reporting) -- closing this.

**Closed by chrisdaaz** 2018-11-28 15:06 UTC
Labels: needs reproduction, user interface
