### ISSUE TITLE
Javascript not functional on collection sharing tab 

### ISSUE THREAD

**Issue by j-dornbusch** [samvera/hyrax#3469] opened 2019-01-10 16:22 UTC
### Descriptive summary

Hyrax v3.0.0-beta1

In the collection 'sharing' tab, as we click the 'add' button to give a permission to a group or to a user, nothing happens, or the form is posted.
The share tabs work in the other contexts (Work, FileSet, Batch upload)

Looking at the code (`/app/views/hyrax/dashboard/collections/_form_share.html.erb` ), the ids of the form elements do not match those expected in es6 classes `UserControls` & `GroupControls` (`#new_user_name_skel`, etc.). 
And there's no js template at the bottom of the erb template like in app/views/hyrax/base/_form_share.html.erb for example. The 'tmpl-collection-grant'  indicated by [this line](https://github.com/samvera/hyrax/blob/b5c6605917c01c51b4504f7e27999146fc584713/app/assets/javascripts/hyrax/app.js.erb#L121) does not exist.
Compare search results for ['tmpl-work-grant'](https://github.com/samvera/hyrax/search?q=tmpl-work-grant&unscoped_q=tmpl-work-grant) and ['tmpl-collection-grant'](https://github.com/samvera/hyrax/search?q=tmpl-collection-grant&unscoped_q=tmpl-collection-grant)

### Expected behavior
The same behavior as the share tab for Works, FileSets and batch uploads.

### Actual behavior
The "add" button has no effect, or the form is posted, as if the application was working in accessible mode. 

### Steps to reproduce the behavior

1. Create a new Collection
2. Save it with the minimal mandatory fields
3. Go to the "sharing" tab
4 Try to add sharing with groups or users.

**Comment by vantuyls** [comment] 2019-02-21 19:23
The issue here is that the Add button does not give any indication that anything has happened, and that the table does not populate with the User or Group that was added. 

On Save, the person/group is added. 

Possible resolutions:
1) have the form populate the table with the user/group that was added to allow the user to see that the Add button has the desired effect
2) add a message upon selecting the Add button indicating that the user should Save for changes to go into effect. 

my preference is 1, but i'm not sure how challenging that is.

**Comment by no-reply** [comment] 2019-09-21 02:54
I can't reproduce this on Firefox 68.0.1.

**Comment by rjkati** [comment] 2021-01-27 14:38
I can't reproduce this in Chrome 87.0.4280.141 or Firefox 85.0 in Hyrax 3.0.0 rc3. It was present in Firefox 84.0.2.
@jlhardes

**Comment by jlhardes** [comment] 2021-01-28 21:47
I just tried in Firefox 84.0.2 and adding users to collections worked. This doesn't seem to be reproducible so I am closing.

**Closed by jlhardes** 2021-01-28 21:47 UTC
Labels: bug, needs reproduction
